### ISSUE TITLE
void

### ISSUE THREAD

**Issue by ghost** [ontio/ontology#1001]

**Comment by Honglei-Cong** [comment]
OK.  @javajoker

**Comment by javajoker** [comment]
The diagram is for the overall architecture of Ontology, while the changeable consensus is just one feature of "Consensus Mechanism" in the diagram.
That's why we didn't put related description in the diagram directly, but add plain text to describe features outside.

Thanks.

**Comment by lazaridiscom** [comment]
@javajoker , this is more something for the Product-Manager:

=> Having a changeable consensus is a Strenth of Ontology

=> This strength should be made immediately visible, e.g. in Diagrams describing the architecture.

See, for me, this fact could be a major decision-point.

May I ask: which other modules/units are changeable?
