### ISSUE TITLE
Consider Switching to "dep"

### ISSUE THREAD

**Issue by ghost** [ontio/ontology#1002]
https://github.com/Masterminds/glide/releases/tag/v0.13.0

> Consider switching to dep
> 
> Glide is used by a great number of projects and will continue to get support for some time. But, the near future is likely in dep. dep can handle importing Glide config files. Please consider trying dep on your project or converting to dep. If you encounter an issue please check if there is an existing bug report and file one if there is not.
> 
> Glide will continue to be supported for some time as there are many users who rely on it and some are not able or ready to move to dep.

**Comment by Honglei-Cong** [comment]
Thanks for the info.
Right, we're planing to move to dep :)

**Comment by ghost** [comment]
I just hit on a glide-problem on windows, that why I filed this here!

**Comment by Honglei-Cong** [comment]
OK.
I'll tried dep.  It's more convenient than glide :)

But Ontology is based on golang 1.9.x currently.  
"Dep" can be enabled officially after upgrading to golang 1.12.x.
It may take some time.

**Comment by ghost** [comment]
Possibly just require !.12+

https://github.com/ontio/ontology#build-development-environment

Dep seems unavoidable anyways.

**Comment by laizy** [comment]
close this since we also support go mod now.
