### ISSUE TITLE
Document Windows Build

### ISSUE THREAD

**Issue by ghost** [ontio/ontology#1023]
It is not exactly clear how to build on Windows.

The README mentions as prerequisites:

* Go
* glide

But it seems that `make` (which one? ) and `docker` are needed, too.

Please clarify this.

**Comment by Honglei-Cong** [comment]
make is not a MUST requirement.
After <code>glide install</code>, you can build with <code>go build main.go</code>.

docker is needed when you build Ontology docker image.

**Comment by Honglei-Cong** [comment]
gomod supported now.
