### ISSUE TITLE
[TestNet] AddBlock error:saveBlock error state merkle root mismatch!

### ISSUE THREAD

**Issue by quocnhan** [ontio/ontology#1051]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
1.6.2

#### Does this issue reproduce with the latest release?
Yes

#### What operating system are you using (such as macOS, Linux and Windows)?
Linux

#### What did you do?
I want to sync with ontology testnet by this command : 
`./ontology-linux-amd64 --networkid 2 --ws --rest --nodeport 20338 --rpcport 20336 --restport 20334 --wsport 20335 -p 123123 -w ./wallet.dat --data-dir ./testnet/`

It sync to block 2428485 and then stop there. I used the latest release 1.6.2 but this bug still there.

![Screenshot from 2019-08-08 14-37-24](https://user-images.githubusercontent.com/33271341/62684090-1f4aea80-b9ea-11e9-84ce-658f93d14861.png)

**Comment by laizy** [comment]
@quocnhan, testnet currently use v1.7.0-beta. see [release notes](https://github.com/ontio/ontology/releases/tag/v1.7.0-beta).  please use that version.

**Comment by quocnhan** [comment]
> @quocnhan, testnet currently use v1.7.0-beta. see [release notes](https://github.com/ontio/ontology/releases/tag/v1.7.0-beta). please use that version.

thanks you. I will try it

**Comment by quocnhan** [comment]
@laizy 
![Screenshot from 2019-08-13 14-15-51](https://user-images.githubusercontent.com/33271341/62922144-ea1d0e80-bdd4-11e9-8835-5afbfb81aa0d.png)
I tested with 1.7.0-beta but it was stoped at 849999

**Comment by laizy** [comment]
@quocnhan ok, we will investigate soon.

**Comment by quocnhan** [comment]
@laizy u still there ?

**Comment by laizy** [comment]
@quocnhan , we have checked the execution of each block in the testnet and mainnet last week, and identified the problem, we are fixing it, maybe it will works tomorrow.

**Comment by quocnhan** [comment]
@laizy btw, do we have any public node testnet which i can use rpc to interact with this network (create tx,signtx,sendtx ) without sync ?

**Comment by quocnhan** [comment]
> @quocnhan , we have checked the execution of each block in the testnet and mainnet last week, and identified the problem, we are fixing it, maybe it will works tomorrow.

tks. hope it work soon

**Comment by laizy** [comment]
> @laizy btw, do we have any public node testnet which i can use rpc to interact with this network (create tx,signtx,sendtx ) without sync ?

yes, we provide the following nodes for testnet, they all support `RPC` , `Restful` and `WebSocket`:
```
http://polaris1.ont.io
http://polaris2.ont.io
http://polaris3.ont.io
http://polaris4.ont.io
http://polaris5.ont.io
```
for more info, you can read this documentation: https://dev-docs.ont.io/#/docs-cn/ontology-cli/03-connect-to-client?id=_3-%e4%bd%bf%e7%94%a8%e5%85%ac%e5%bc%80%e8%8a%82%e7%82%b9

**Comment by quocnhan** [comment]
@laizy I used postman to get block 100 but it Could not get any response . Could you help me ?
![Screenshot from 2019-08-21 09-25-57](https://user-images.githubusercontent.com/33271341/63397837-fcf79a80-c3f5-11e9-8358-f218e63bc457.png)
![Screenshot from 2019-08-21 09-28-21](https://user-images.githubusercontent.com/33271341/63397860-0d0f7a00-c3f6-11e9-85d3-5ee6697c226a.png)

**Comment by quocnhan** [comment]
> @laizy I used postman to get block 100 but it Could not get any response . Could you help me ?
> ![Screenshot from 2019-08-21 09-25-57](https://user-images.githubusercontent.com/33271341/63397837-fcf79a80-c3f5-11e9-8358-f218e63bc457.png)
> ![Screenshot from 2019-08-21 09-28-21](https://user-images.githubusercontent.com/33271341/63397860-0d0f7a00-c3f6-11e9-85d3-5ee6697c226a.png)

i try method post and get, from node 1 to 5 but all of them not response to me

**Comment by laizy** [comment]
use port 20334 for restful api, like:http://polaris2.ont.io:20334/api/v1/block/details/height/100

**Comment by laizy** [comment]
@quocnhan, could you restart ontology 1.7.0-beta to help me confirm it works now?  It should continue sync blocks after 849999.

**Comment by quocnhan** [comment]
@laizy perfect, it work now. Let me sync and test with it. Tks for your support

**Comment by quocnhan** [comment]
@laizy in mainnet, we should use 1.6.2, right ?

**Comment by laizy** [comment]
yes.

**Comment by quocnhan** [comment]
@laizy thank you. Everything work. I will close this issue !
