### ISSUE TITLE
Some transactions of OEP4 assets doesn't work with a certain amount

### ISSUE THREAD

**Issue by deblanco** [ontio/ontology#1061]
Hello team,

We are having problems performing some transactions with an OEP4 token. We noticed with a certain amount of tokens is happening (happening = the transaction is not performed), and after days of analysis, we didn't find the logic that triggers this error.

The issue is happening in **mainnet** and in **testnet**.

The contracts having this problem are the next:
- Mainnet: 78b98deed62aa708eaf6de85843734ecdfb14c1b
- Testnet: d01be91dd3d9c0f09cedef20298e73109a788397

We are able to reproduce this behaviour with _Owallet_ and _ontology-ts-sdk_, with this last one we did it using the methods for single and multi transactions.

With Multi transaction we get an error: `[NeoVmService] vm execution encountered a state fault!`, but with Single transaction we see that the transaction is executed but without the token only with the ONG fee.

The following amounts trigger the error:
16629180
10947017
10274403
63522
59494
56739
54958
53638
53553
46283
44712
40835
40358
37297
27646
27490
27284
351
259
255
250
247
237
230
227
226
225
224
223
222
221
220
219
218
217
168

This is one of the scripts that we use to do Multi transactions: https://github.com/deblanco/ontology-airdrop

Thanks in advance!
Daniel

**Comment by WyattMufson** [comment]
I can also confirm that this exists - I tested the same contract through [neovmutils](https://github.com/Ryucoin/neovm-utils)

**Comment by WyattMufson** [comment]
A link to the most up to date version of the contracts will most likely be needed to make sure it's not a contract level error (the one I was given had a comment in `transfer` that was missing the opening `"""`)

**Comment by deblanco** [comment]
Seems to be fixed with the last version of ontology-ts-sdk.
Could someone from the ontio team confirm this?

Thanks

**Comment by laizy** [comment]
yes, it has been fixed in the last version of ontology-ts-sdk. please update the Owallet to the last version.
