### ISSUE TITLE
No asset in bookkeeper nodes on local network

### ISSUE THREAD

**Issue by dmarii** [ontio/ontology#1087]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
The most recent version built from source code.
1.7.0 beta

#### Does this issue reproduce with the latest release?
Yes, I also tried using the newest release version

#### What operating system are you using (such as macOS, Linux and Windows)?
macOS

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

I tried setting up a local testnet with 4 nodes and DBFT consensus, and I specified those 4 nodes as bookkeepers in my config file. 
I was able to initialize this private network on my computer, and the 4 nodes run and generate new blocks as expected. However, none of the 4 nodes has ONT.

For all the four nodes, I used a network id of 1000, which is not equal to 1/2/3, and I did not use --testmode flag because testmode would set it to solo consensus, which is not what I want. I also set all the ports so there is no conflicts.

#### What did you expect to see?
The four bookkeepers should have ONT after initialization.

#### What did you see instead?
The four nodes have 0 for both ONT and ONG.

#### Additional context

I also tried setting up 7 nodes with VBFT and a different config file, however, same thing happened and none of them had any asset. 
In addition to that, I was able to setup an additional node as sync node, but this new node does not have asset as well.
I believe this issue has the similar problem here: https://github.com/ontio/ontology/issues/220

**Comment by laizy** [comment]
the ONT is initialized in a multi-address of the bookkeepers, the minimal signature required is 	`m := (5*len(bookkeepers) + 6) / 7`.  so if you use 4 nodes, m = 3, you can use `/ontology multisignaddr -m 3 --pubkey pk1,pk2,pk3,pk4` to get the multiaddr.
