### ISSUE TITLE
Get contract state from store failed

### ISSUE THREAD

**Issue by NashMiao** [ontio/ontology#1090]
#### What version of ontology are you using (`ontology --version`)?

- dappnode1.ont.io
- dappnode2.ont.io
- dappnode3.ont.io

```bash
$ GET http://dappnode1.ont.io:20334/api/v1/version
{
    "Action": "getversion",
    "Desc": "SUCCESS",
    "Error": 0,
    "Result": "v1.7.2-0-g2377759",
    "Version": "1.0.0"
}
```

#### Does this issue reproduce with the latest release?

Yes.

#### What operating system are you using (such as macOS, Linux and Windows)?

Linux and Windows.

#### What did you do?

```bash
$ GET http://dappnode1.ont.io:20334/api/v1/contract/d3b733f12df9a6efb13ca547be5ee4e4dbe6d41e
{
    "Action": "getcontract",
    "Desc": "INTERNAL ERROR",
    "Error": 45001,
    "Result": "",
    "Version": "1.0.0"
}
```

![image](https://user-images.githubusercontent.com/18191964/66473772-85bfb800-eac2-11e9-9435-464d1bc5c2b9.png)

#### What did you expect to see?

Getting the contract information from blockchain. Because this contract exist in main net.

```bash
$ GET https://dappnode1.ont.io:10334/api/v1/smartcode/event/txhash/7ddeeb5e1513131d49ff44cd66dd391aae6b8b0ecc5e38eb5689104a29907d8f
{
  "Action": "getsmartcodeeventbyhash",
  "Desc": "SUCCESS",
  "Error": 0,
  "Result": {
    "TxHash": "7ddeeb5e1513131d49ff44cd66dd391aae6b8b0ecc5e38eb5689104a29907d8f",
    "State": 1,
    "GasConsumed": 10000000,
    "Notify": [
      {
        "ContractAddress": "d3b733f12df9a6efb13ca547be5ee4e4dbe6d41e",
        "States": [
          "61646450616972",
          "01",
          "4f4e54",
          "0000000000000000000000000000000000000001",
          "00",
          "4f4e47",
          "0000000000000000000000000000000000000002",
          "09",
          "00ca9a3b"
        ]
      },
      {
        "ContractAddress": "0200000000000000000000000000000000000000",
        "States": [
          "transfer",
          "AMcGNrCtVYoiqVA36LYZYzcG4uAryL2LA9",
          "AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",
          10000000
        ]
      }
    ]
  },
  "Version": "1.0.0"
}
```

![image](https://user-images.githubusercontent.com/18191964/66474011-08487780-eac3-11e9-9cb5-24506b46818d.png)

#### What did you see instead?

I can't get contract information by this API.

![image](https://user-images.githubusercontent.com/18191964/66474286-915fae80-eac3-11e9-97fd-cab257a6b643.png)

![image](https://user-images.githubusercontent.com/18191964/66474408-d5eb4a00-eac3-11e9-96e9-1f32cc69c84d.png)

However, we can find this contract's event in height `2212012`. That is to say, we should find the contract information from LevelDB in this height.

```bash
GET https://dappnode1.ont.io:10334/api/v1/block/height/txhash/7ddeeb5e1513131d49ff44cd66dd391aae6b8b0ecc5e38eb5689104a29907d8f
{
  "Action": "getblockheightbytxhash",
  "Desc": "SUCCESS",
  "Error": 0,
  "Result": 2212012,
  "Version": "1.0.0"
}
```

![image](https://user-images.githubusercontent.com/18191964/66474734-780b3200-eac4-11e9-9ebd-de15e6fda050.png)

**Comment by laizy** [comment]
after some investigation, I found the contract is migrated by transaction `2924e99231dbb8386a48cab7f581af578b3f985349e2df8edacf20bb0a314f0b`

the invoke code is something like: 
![image](https://user-images.githubusercontent.com/4203231/66478094-2ebee080-eacc-11e9-8eb9-e7ef0f55b597.png)

**Comment by NashMiao** [comment]
Thanks very much, maybe this [link](https://github.com/ontio/ontology/blob/ca9abcf108728d12cccd6c61a898169e6d4edf37/smartcontract/service/neovm/contract.go#L50) is helpful, if others want to know more information.
