### ISSUE TITLE
Why ont does not use rfc6979 to generate K value when signing

### ISSUE THREAD

**Issue by vae520283995** [ontio/ontology#1118]
Why ont does not use rfc6979 to generate K value when signing

**Comment by AlverLyu** [comment]
Deterministic ECDSA is a new standard and may not be supported in some environment. Thus using the original ECDSA can have better compatibility and interoperability.

**Comment by AlverLyu** [comment]
Anyway, a signature generated as rfc6979 is also valid in Ontology. There is not difference in validation.
