### ISSUE TITLE
Can't build ontology.

### ISSUE THREAD

**Issue by monaka** [ontio/ontology#1145]
#### What version of ontology are you using (`ontology --version`)?

Can't build the binary. Information about the git repo is here.

```
$ git log -1 
commit da60191a026669fd9a24bd55ee8eac47f5fbda77 (HEAD -> master, tag: v1.8.2-alpha, tag: v1.8.2, origin/wasmjit, origin/master, origin/cross-chain, origin/HEAD)
Author: laizy <laizy@users.noreply.github.com>
Date:   Thu Dec 26 10:16:46 2019 +0800

    replace go-interpreter/wagon to ontio/wagon (#1141)
```

#### Does this issue reproduce with the latest release?

```
$ go version
go version go1.13.5 linux/amd64
$ go get github.com/ontio/ontology
# github.com/ontio/ontology
./sigsvr.go:111:6: main redeclared in this block
        previous declaration at ./main.go:136:6
```

#### What operating system are you using (such as macOS, Linux and Windows)?

Linux

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

#### What did you expect to see?

Done with no error.

#### What did you see instead?

See above in this report.

#### Additional context

None.

**Comment by Honglei-Cong** [comment]
Please try `make ontology`

**Comment by monaka** [comment]
@Honglei-Cong Yes `make ontology` works.
And the my goal is to run `make docker`. This issue is simplified against my goal.
