### ISSUE TITLE
why sending FindNodeReq of curPair.ID to itself? 

### ISSUE THREAD

**Issue by Honglei-Cong** [ontio/ontology#1184]
https://github.com/ontio/ontology/blob/f710def71a488e81b71c5364327145bb65e29044/p2pserver/protocols/discovery/discovery.go#L91

should sending FindNodeReq of self.ID to curPair.ID ?

**Comment by laizy** [comment]
should be `self.ID`. @rongyi

**Comment by rongyi** [comment]
yes, it should be self.id, pr 1185 fix this.
