### ISSUE TITLE
getversion has no printout

### ISSUE THREAD

**Issue by lcgogo** [ontio/ontology#1192]
Please answer these questions before submitting your issue. Thanks!

curl --data-binary '{"jsonrpc": "2.0", "id": "curltext", "method": "getversion", "params": []}' -H 'content-type:text/plain;'

{"desc":"SUCCESS","error":0,"id":"curltext","jsonrpc":"2.0","result":""}

#### Does this issue reproduce with the latest release?
1.8.2 and  1.9.0

#### What operating system are you using (such as macOS, Linux and Windows)?
ubuntu

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

**Comment by laizy** [comment]
could you run `./ontology --version` and paste the output here? I think you did not  build the `ontology` binary with `make ontology`.

**Comment by lcgogo** [comment]
> could you run `./ontology --version` and paste the output here? I think you did not build the `ontology` binary with `make ontology`.

docker exec -it ont-1.9.0 /bin/ontology --version
ontology version

no printout too.

I use docker golang:1.14-buster as builder and run make all instead of make ontology

**Comment by laizy** [comment]
@lcgogo can you provide your docker file? the version is set at compile time based on git tag. so you need make sure clone the repo with tags. for example `git clone https://github.com/ontio/ontology.git -b v1.9.0`

**Comment by lcgogo** [comment]
I use the tar.gz from release, but not the git. Maybe the reason.

\# Build image
FROM golang:1.14-buster as builder

ENV COIN_NAME=ont
ARG COIN_VERSION=master

WORKDIR /go/src
RUN go get github.com/Masterminds/glide
RUN wget -O ${COIN_NAME}-${COIN_VERSION}.tar.gz https://github.com/ontio/ontology/archive/v${COIN_VERSION}.tar.gz \
    && tar -zxf ${COIN_NAME}-${COIN_VERSION}.tar.gz \
    && mkdir github.com/ontio/ \
    && mv ontology-${COIN_VERSION} github.com/ontio/ontology \
    && cd github.com/ontio/ontology \
    && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    && glide install && make all

\# Production image
FROM debian:stable-slim
COPY --from=builder /go/src/github.com/ontio/ontology/ontology /bin/
\# 20336 rpc
\# 20338 p2p
EXPOSE 20336 20338
VOLUME /data/ont
CMD ["/bin/ontology", "--data-dir", "/data/ont"]

**Comment by Honglei-Cong** [comment]
aha, ontology version is from git tags.
If your code is not in git, there'll no version info.

**Comment by Honglei-Cong** [comment]
@laizy 
I think we should update `config.Version` when starting a new release cycle.

**Comment by laizy** [comment]
addressed in #1211 .
