### ISSUE TITLE
Does the mainnet need to be upgraded to 2.0 now?

### ISSUE THREAD

**Issue by zenghq3** [ontio/ontology#1245]
[https://github.com/ontio/ontology/releases/tag/v2.0.0](url) says All nodes need to be upgraded,but it currently running on testnet.

**Comment by laizy** [comment]
v2.0.0 is still in pre-release state. All nodes running on testnet need to be upgraded now.  and the mainnet is still in v1.10.0 version, and will start upgrade soon, when all consensus nodes in mainnet are upgraded, we will change the release note.

**Comment by zenghq3** [comment]
thx
