### ISSUE TITLE
Can not run command 'make all' in Windows

### ISSUE THREAD

**Issue by grindydev** [ontio/ontology#1252]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
Latest

#### Does this issue reproduce with the latest release?
Yes

#### What operating system are you using (such as macOS, Linux and Windows)?
Windows

#### What did you do?
I clone project from github and run command 'make all'
If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

#### What did you expect to see?
two executable programs

#### What did you see instead?
alot warning and error with ending:

collect2.exe: error: ld returned 1 exit status
Makefile:18: recipe for target 'ontology' failed
make: *** [ontology] Error 2

**Comment by laizy** [comment]
we use cgo in ontology, and golang's cgo feature is not well supported for windows. you can use WSL instead.
