### ISSUE TITLE
Import ontology-go-sdk package fail in ontology

### ISSUE THREAD

**Issue by grindydev** [ontio/ontology#1256]
#### What version of ontology are you using (`ontology --version`)?
Latest

#### What operating system are you using (such as macOS, Linux and Windows)?
Linux

#### What did you do?
I trying to import package ontology-go-sdk in my test project

#### What did you expect to see?
Import successful

#### What did you see instead?
# github.com/ontio/ontology/cmd/utils
../github.com/ontio/ontology/cmd/utils/flags.go:507:14: flag.GetName undefined (type cli.Flag has no field or method GetName)

**Comment by laizy** [comment]
do you use go module? we use package urfave/cli v1.22.1, GetName is defined at:
https://github.com/urfave/cli/blob/v1.22.1/flag.go#L74 
 you may misused an newer version .

**Comment by grindydev** [comment]
problem solved
