### ISSUE TITLE
staticcheck show us some useful warnings

### ISSUE THREAD

**Issue by rongyi** [ontio/ontology#1276]
using [staticcheck](https://staticcheck.io/) to lint ontology code, beside the naming convention warnings, there are some useful hint for us, here are some sample output:

core/store/ledgerstore/ledger_store.go:388:2: redundant return statement (S1023)
core/store/ledgerstore/ledger_store.go:860:29: func (*LedgerStoreImp).tryGetSavingBlockLock is unused (U1000)
core/store/ledgerstore/ledger_store.go:1289:8: should use bytes.Equal(wasmMagicversion, deploy.GetRawCode()[:8]) instead (S1004)
core/store/ledgerstore/ledger_store_test.go:37:1: TestMain should call os.Exit to set exit code (SA3000)
core/store/ledgerstore/state_store.go:440:22: should use make([]byte, 5) instead (S1019)
core/store/ledgerstore/tx_handler.go:150:18: should use bytes.Equal(code, ninit.COMMIT_DPOS_BYTES) instead (S1004)
core/store/ledgerstore/tx_handler_test.go:62:6: func add is unused (U1000)
core/store/leveldbstore/leveldb_store_test.go:28:1: TestMain should call os.Exit to set exit code (SA3000)
core/store/overlaydb/iterator.go:53:5: should omit comparison to bool constant, can be simplified to !f (S1002)
core/store/overlaydb/iterator.go:57:6: should omit comparison to bool constant, can be simplified to !iter.next() (S1002)
core/store/overlaydb/iterator.go:76:6: should omit comparison to bool constant, can be simplified to !mem (S1002)
core/store/overlaydb/iterator.go:120:5: should omit comparison to bool constant, can be simplified to !f (S1002)
core/store/overlaydb/iterator.go:125:6: should omit comparison to bool constant, can be simplified to !iter.next() (S1002)
core/store/overlaydb/iterator.go:134:66: should omit comparison to bool constant, can be simplified to !iter.nextMemEnd (S1002)
core/store/overlaydb/iterator.go:137:67: should omit comparison to bool constant, can be simplified to !iter.nextBackEnd (S1002)
core/store/overlaydb/memdb.go:315:2: redundant return statement (S1023)
core/store/overlaydb/overlaydb.go:61:5: should omit comparison to bool constant, can be simplified to !unknown (S1002)
core/types/transaction.go:311:5: should omit comparison to bool constant, can be simplified to !tx.nonDirectConstracted (S1002)
core/types/transaction_attribute.go:64:10: error strings should not be capitalized (ST1005)
core/types/transaction_attribute.go:64:10: error strings should not end with punctuation or a newline (ST1005)
core/types/transaction_attribute.go:78:10: error strings should not end with punctuation or a newline (ST1005)
core/utils/transaction_builder.go:249:16: error strings should not end with punctuation or a newline (ST1005)
core/validation/block_validator.go:69:12: should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)) (S1028)
core/validation/block_validator.go:69:23: unnecessary use of fmt.Sprintf (S1039)
core/validation/block_validator.go:73:12: should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)) (S1028)
core/validation/block_validator.go:73:23: unnecessary use of fmt.Sprintf (S1039)
core/validation/block_validator.go:87:10: error strings should not end with punctuation or a newline (ST1005)
core/validation/block_validator.go:91:10: error strings should not end with punctuation or a newline (ST1005)
core/validation/block_validator.go:95:10: error strings should not end with punctuation or a newline (ST1005)
core/validation/transaction_validator.go:101:5: should omit comparison to bool constant, can be simplified to !address[tx.Payer] (S1002)
errors/callstack.go:45:10: unnecessary use of fmt.Sprintf (S1039)
errors/errors_test.go:28:2: error var TestRootError should have name of the form ErrFoo (ST1012)
errors/errors_test.go:28:18: error strings should not be capitalized (ST1005)
errors/errors_test.go:28:18: error strings should not end with punctuation or a newline (ST1005)
events/event.go:59:9: error strings should not be capitalized (ST1005)
events/event.go:59:9: error strings should not end with punctuation or a newline (ST1005)
events/event.go:76:9: error strings should not be capitalized (ST1005)
events/event.go:76:9: error strings should not end with punctuation or a newline (ST1005)
http/base/rest/interfaces.go:267:2: should merge variable declaration with assignment on next line (S1021)
http/nodeinfo/prom.go:112:2: should use for range instead of for { select {} } (S1000)
http/restful/restful/router.go:51:7: should omit comparison to bool constant, can be simplified to !match (S1002)
http/restful/restful/router.go:74:3: unnecessary nil check around range (S1031)
http/restful/restful/router.go:123:42: should not use built-in type string as key for value; define your own type to avoid collisions (SA1029)
http/restful/restful/router.go:141:2: unnecessary assignment to the blank identifier (S1005)
http/restful/restful/server.go:188:68: cutset contains duplicate characters (SA1024)
http/restful/restful/server.go:190:71: cutset contains duplicate characters (SA1024)
http/restful/restful/server.go:192:66: cutset contains duplicate characters (SA1024)
http/restful/restful/server.go:194:69: cutset contains duplicate characters (SA1024)
http/restful/restful/server.go:196:60: cutset contains duplicate characters (SA1024)

do we need to fix this?

**Comment by laizy** [comment]
> do we need to fix this?

yes, we should fix this.

**Comment by rongyi** [comment]
> > do we need to fix this?
> 
> yes, we should fix this.

OK, I'll send some PR for this issue

**Comment by laizy** [comment]
fixed in #1277
