### ISSUE TITLE
block stop at 11703054,how fix

### ISSUE THREAD

**Issue by zhangsj** [ontio/ontology#1301]
block stop at 11703054,how fix

2021/03/24 06:00:17.951082 [ERROR] GID 3575, Ledger AddBlock BlockHeight:11703055 BlockHash:779640eb7ce52f8dd16a13e14cc3619a93fcc60b1a47aeb207c1f4a0a9e27760 error:saveBlock error state merkle root mismatch. expected: 8c9a2283025da7dea44f8adf1d7753a0233bd4758fcda1cdcf564649aa044200, got: ea51d4b7f7a188a797745ea7c6ba97e09aacbf2bf93b804c45c51b2b438683cb
2021/03/24 06:00:17.951101 [WARN ] GID 3575, [block-sync] saveBlock Height:11703055 AddBlock error:saveBlock error state merkle root mismatch. expected: 8c9a2283025da7dea44f8adf1d7753a0233bd4758fcda1cdcf564649aa044200, got: ea51d4b7f7a188a797745ea7c6ba97e09aacbf2bf93b804c45c51b2b438683cb
2021/03/24 06:00:21.691920 [INFO ] GID 69, CurrentBlockHeight = 11703054
2021/03/24 06:00:26.530441 [INFO ] GID 4182, state mismatch at block height: 11703055, changeset: digraph g {
				graph [
				rankdir = "LR"
				style="filled"
				];
				node [
				fontsize = "16"
				shape = "ellipse"
				style="filled"
				];
"n0" [
	shape = "record"
	label = "<f1> 1 | :"];
"n16" [
	shape = "record"
	label = "<f1> 1 | 0500000000000000000000000000000000000000020000000000000000000000000000000000000007:000869c0d164f92f2c00"];
"n21" [
	shape = "record"
	label = "<f1> 1 | 0500000000000000000000000000000000000000021c401d12a29b4b077ca1fa4ae2616968484d68d1:000800b5a3fa01000000"];
"n0":f1 -> "n16":f1 ;
"n16":f1 -> "n21":f1 ;
}
2021/03/24 06:00:26.530522 [ERROR] GID 4182, Ledger AddBlock BlockHeight:11703055 BlockHash:779640eb7ce52f8dd16a13e14cc3619a93fcc60b1a47aeb207c1f4a0a9e27760 error:saveBlock error state merkle root mismatch. expected: 8c9a2283025da7dea44f8adf1d7753a0233bd4758fcda1cdcf564649aa044200, got: ea51d4b7f7a188a797745ea7c6ba97e09aacbf2bf93b804c45c51b2b438683cb
2021/03/24 06:00:26.530540 [WARN ] GID 4182, [block-sync] saveBlock Height:11703055 AddBlock error:saveBlock error state merkle root mismatch. expected: 8c9a2283025da7dea44f8adf1d7753a0233bd4758fcda1cdcf564649aa044200, got: ea51d4b7f7a188a797745ea7c6ba97e09aacbf2bf93b804c45c51b2b438683cb
2021/03/24 06:00:27.691878 [INFO ] GID 69, CurrentBlockHeight = 11703054
2021/03/24 06:00:33.691821 [INFO ] GID 69, CurrentBlockHeight = 11703054
2021/03/24 06:00:39.691876 [INFO ] GID 69, CurrentBlockHeight = 11703054
2021/03/24 06:00:45.691876 [INFO ] GID 69, CurrentBlockHeight = 11703054
2021/03/24 06:00:51.691909 [INFO ] GID 69, CurrentBlockHeight = 11703054

**Comment by laizy** [comment]
please upgrade ontology to new version [v2.2.0](https://github.com/ontio/ontology/releases/tag/v2.2.0).

**Comment by limengyang-boy** [comment]
Has the problem been solved?
