### ISSUE TITLE
The block update stops at 11,703,054 and is no longer updated. The version has been upgraded to 2.2.0

### ISSUE THREAD

**Issue by limengyang-boy** [ontio/ontology#1302]
![image](https://user-images.githubusercontent.com/75056837/112612353-cac3df80-8e59-11eb-8413-325e0906941a.png)

**Comment by laizy** [comment]
because you are using a reserved file, and reject to connect with other peers. you need update your peers.rsv file, or disable it.

you can try to just use:
```
./ontology
```
