### ISSUE TITLE
P2P Error

### ISSUE THREAD

**Issue by MaxxGit** [ontio/ontology#1307]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
ontology version v2.1.1-alpha-13-g7c67e8b

#### Does this issue reproduce with the latest release?
Yes

#### What operating system are you using (such as macOS, Linux and Windows)?
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

#### What did you do?
I am setting up a node

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

#### What did you expect to see?
No errors in log

#### What did you see instead?
I read many errors in my log files:
2021/05/11 15:27:17.708456 [INFO ] GID 1939457, [p2p]error read from 170.106.111.251:20338 :read tcp 95.110.226.153:38360->170.106.111.251:20338: use of closed network connection

where 95.110.226.153 is the IP of my node

**Comment by laizy** [comment]
This is OK, since network errors are inevitable. For example,：
1. the connection between two nodes is unstable;
2. the remote node's connections is full;
3. the remote node has set reserved peers, which limit the node's  IP address connected to it.

**Comment by MaxxGit** [comment]
> This is OK, since network errors are inevitable. For example,：
> 
> 1. the connection between two nodes is unstable;
> 2. the remote node's connections is full;
> 3. the remote node has set reserved peers, which limit the node's  IP address connected to it.

Thanks Laizy
