### ISSUE TITLE
Address AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK returns 503 api server error

### ISSUE THREAD

**Issue by sawyerru** [ontio/ontology#1363]
I'm using the API to interaction and with information from the nodes. When I hit the transactions by time endpoint for the above address I often get 503 Service Unavailable issues: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

It's clear from the UI that this account runs about 1-3k transactions/day so this is a significant amount of data to collect with the API. My best thought is that this amount of stress causes a failure in the API server for the connection to timeout.

I'm mostly interested in determining if this is some internal Ontology smart contract address that is used to funnel funds or something. If it is not I would like to solve the 503 error from this call.

API CALL: https://explorer.ont.io/v2/addresses/AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK/ONT/transactions?begin_time=1627317078&end_time=1627403478

Error Response:
The site you have attempted to access was unreachable - The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
![image](https://user-images.githubusercontent.com/30737015/128870926-5793adbb-d4e1-4388-80b1-048dc76b7d16.png)

Thanks

**Comment by rongyi** [comment]
thank you for pointing out, we'll check the config and give you the response asap

**Comment by rongyi** [comment]
we've searched our backend log didn't find any 503 error log about your request, our server's default timeout time is 60 seconds, pls set the client timeout accordingly.

**Comment by sawyerru** [comment]
Thanks rongyi for checking. I'll update the client timeout to handle that 60 second limit. Closing the issue. Thanks!
