### ISSUE TITLE
Network Fee Incentive for the month of July not paid to non-top-49 candidate nodes

### ISSUE THREAD

**Issue by MaxxGit** [ontio/ontology#1365]
Hi, my “Colosseum” node did not receive the Network Fee Incentive for the month of July while the top 49 nodes received both the monthly reward and the foundation bonus. 

This is the link to my node: https://node.ont.io/detail/02798509ab45d6568c6ac60cfe8c832fae88513760c5362c05337f0bc3585b4a51/AG7y887MSLxrcTKpvosRUnkptgxgGMZ7p6/balance. As you can see in the last "transfer" tab, between transactions there is no ONG incoming movement of 10 August for the monthly reward.  For the top-49 nodes instead there are.  The whitepaper is clear, all candidate nodes receive the monthly reward, like the previous months.

Can you disburse ONG due to non-top 49 candidate nodes as well?
Thanks

**Comment by OntologyTech** [comment]
The monthly Ontology Foundation bonus will be shared amongst only the top 49 nodes and distributed manually by the Ontology Foundation.  The Ontology Foundation issued this incentive for July on 10 August.
Network fee incentive and Released ONG incentive will be shared amongst all 343 Triones nodes.  You should use OWallet to claim this part by yourself.
