### ISSUE TITLE
how can I get the standart node sync status?

### ISSUE THREAD

**Issue by gitloverr** [ontio/ontology#1366]
hi everyone,

I would like to get the my standart node sync status over rpc api or cli... I couldn't see any method in ontology document.

how can I do this?

thank you

**Comment by lucas7788** [comment]
> hi everyone,
> 
> I would like to get the my standart node sync status over rpc api or cli... I couldn't see any method in ontology document.
> 
> how can I do this?
> 
> thank you

this is the ontology cli doc,  https://github.com/ontio/ontology/blob/master/docs/specifications/cli_user_guide.md

**Comment by laizy** [comment]
@gitloverr you can get the current synced block number by [get_blk_height](https://github.com/ontio/ontology/blob/master/docs/specifications/restful_api.md#5-get_blk_height)

**Comment by gitloverr** [comment]
no I would like to get only synced or not information for node. @lucas7788 ,  the document isn't include this.

**Comment by laizy** [comment]
@gitloverr you can use `/api/v1/node/syncstatus` restful api for this. it will return the current synced block height and the max block height of remote peers.
