### ISSUE TITLE
socket connection closing after a while

### ISSUE THREAD

**Issue by gitloverr** [ontio/ontology#1368]
hi everyone,

I'm connecting the my node over websocket port via **subscribe method** and listening ontology transactions. but my connection closing after a while...

**can I set the socket port connection count as** **unlimited**? I see -**-max-conn-in-bound-single-ip**  parameter in your api document. I set it 99999999999999.  but can I set as direct unlimited? If yes, how? 

thank you

**Comment by laizy** [comment]
you should send some requests or heartbeat message to the remote peer regularly to avoid session timeout, currently set to 5 minutes.
