### ISSUE TITLE
Why there are two different versions of ontology, v2.3.5 and v1.14.2, which version should I use?

### ISSUE THREAD

**Issue by vae520283995** [ontio/ontology#1392]
@laizy please help

**Comment by laizy** [comment]
use v2.3.5 if you just want compile and run ontology. v1.14.2 is used as a lib by other projects like go sdk , [ontology-rosetta](https://github.com/ontio/ontology-rosetta)

**Comment by vae520283995** [comment]
> use v2.3.5 if you just want compile and run ontology

ok, thank you
