### ISSUE TITLE
v2.3.6, All nodes need upgrade

### ISSUE THREAD

**Issue by vae520283995** [ontio/ontology#1400]
When exactly is the upgrade?
@laizy please look at this

**Comment by laizy** [comment]
Sorry for late reply, v2.3.6 is a pre-release to hot fix a corner case. please upgrade to v2.3.7.

**Comment by vae520283995** [comment]
> Sorry for late reply, v2.3.6 is a pre-release to hot fix a corner case. please upgrade to v2.3.7.

So when will you upgrade to v2.3.7?

**Comment by laizy** [comment]
@vae520283995 , we already upgraded to v2.3.7, see the release note. you can also subscribe our marketing twitter: https://twitter.com/OntologyNetwork/status/1507235395808817152

**Comment by vae520283995** [comment]
> @vae520283995，我们已经升级到 v2.3.7，请参阅发行说明。您也可以订阅我们的营销推特：[https ://twitter.com/OntologyNetwork/status/1507235395808817152](https://twitter.com/OntologyNetwork/status/1507235395808817152)

okay, thank you
