### ISSUE TITLE
go install error

### ISSUE THREAD

**Issue by sailaoda** [ontio/ontology#1413]
# github.com/ontio/ontology/smartcontract/service/wasmvm
smartcontract\service\wasmvm\wasmjit_runtime.go:132:104: cannot use _Ctype_ulong(20) (constant 20 of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
smartcontract\service\wasmvm\wasmjit_runtime.go:201:106: cannot use _Ctype_ulong(len(itemWrite)) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration

os:windows11
go version: go1.19.3

**Comment by laizy** [comment]
please use WSL on windows.

**Comment by sailaoda** [comment]
> 
thank you very much!
