### ISSUE TITLE
Public node stuck at 16474666

### ISSUE THREAD

**Issue by Ljzn** [ontio/ontology#1433]
Hello, we're using the public node http://dappnode1.ont.io:20334 to sync the block data. The best block stuck at 16474666, could you help to fix it?

**Comment by laizy** [comment]
@Ljzn Have you upgraded the node to the newest version? Please provide the node version using `ontology --version`.

**Comment by Ljzn** [comment]
@laizy sorry, it's not my node, is a public node I found from here https://docs.ont.io/developer-tools/api#ontology-mainnet

**Comment by laizy** [comment]
I have queried that node, the height is 16496260 now, and matches the latest block height.
