### ISSUE TITLE
common/password/password.go import github.com/howeyc/gopass,but glide import github.com/dnaproject/gopass

### ISSUE THREAD

**Issue by jxzsxsp** [ontio/ontology#186]
[root@VM_143_245_centos ontology]# make
go build -ldflags "-X github.com/ontio/ontology/common/config.Version=v0.8" -o ontology main.go
common/password/password.go:26:2: cannot find package "github.com/howeyc/gopass" in any of:
/data/gopath/src/github.com/ontio/ontology/vendor/github.com/howeyc/gopass (vendor tree)
/usr/local/go/src/github.com/howeyc/gopass (from $GOROOT)
/data/gopath/src/github.com/howeyc/gopass (from $GOPATH)
make: *** [ontology] 错误 1

**Comment by Arbio5zt** [comment]
thanks for reporting, there seems something lost in glide.yaml, I will have a look on this.

**Comment by Arbio5zt** [comment]
fixed by [commit 5d022a0f65b987af54e0496b169222ffe479eb8a](https://github.com/ontio/ontology/commit/5d022a0f65b987af54e0496b169222ffe479eb8a)
