### ISSUE TITLE
求助，我按照教程使用./ontology --nodeport=20338 --rpcport=201336 报以下错误

### ISSUE THREAD

**Issue by GalaxySciTech** [ontio/ontology#189]
2018/05/20 20:00:16.773104 [INFO ] GID 1, Wait for minimum connection...
2018/05/20 20:00:19.622144 [ERROR] GID 1021, connect failed:  dial tcp 127.0.0.1:20318: connect: connection refused

**Comment by Arbio5zt** [comment]
fixed by [commit 3324736] (https://github.com/ontio/ontology/commit/3324736e54c4a62c579be254ac85239801b13f0d) could you helps to check it agian, thanks.

**Comment by pai01234** [comment]
2018/05/23 21:42:33.065913 [INFO ] GID 1, Wait for minimum connection...
2018/05/23 21:42:33.066056 [INFO ] GID 1, P2P node init success
2018/05/23 21:42:33.066264 [INFO ] GID 1, ConsensusType:dbft
2018/05/23 21:42:33.066366 [INFO ] GID 1, Consensus init success
2018/05/23 21:42:33.066540 [INFO ] GID 218, [ConsensusContext] Calculate Bookkeepers from db
2018/05/23 21:42:33.066621 [ERROR] GID 1, initRpc error:ListenAndServe error:listen tcp: address 201336: invalid port
2018/05/23 21:42:33.066648 [INFO ] GID 218, You aren't bookkeeper

**Comment by GalaxySciTech** [comment]
可以了，thanks
