### ISSUE TITLE
用0.8版多机部署后没有生成ONT资产

### ISSUE THREAD

**Issue by jxzsxsp** [ontio/ontology#220]
[root@VM_143_245_centos multi-node1]# ./ontology asset balance 1
BalanceOf:TA86DZm9hVoqYmedZMVamWLvSCXQF942S6
ONT:0
ONG:0
ONGApprove:0

**Comment by Arbio5zt** [comment]
By public test chain, you need to apply for test ont tokens.
By private ontology blockchain, only bookkeeper node will be given the ONT tokens, so you need to add your node's public key into the config.json file.

**Comment by jxzsxsp** [comment]
config.json中添加了公钥

[root@VM_143_245_centos multi-node1]# cat config.json
{
  "SeedList": [
    "127.0.0.1:20348",
    "127.0.0.1:20358",
    "127.0.0.1:20368",
    "127.0.0.1:20378"
  ],
  "ConsensusType":"dbft",
  "DBFT":{
    "Bookkeepers": [
      "1202029ad0f87ad84b84b085b610475f5c4e409a7744c3732042a0498adf0a251dfde9",
      "1202031afd1e43360c0034e371697b5bf2aff49983e134ee9c7a914050fa6bf1c08ff3",
      "120202e02d15c14a19a2d32b4bd2e921ffc314cefacfc37a04ff94ddfe050299f060ee",
      "120202d7b1de03d7538f2e982f3104165ad756563456d4d4da10d936fbb98195e72a08"
    ],
    "GenBlockTime":6
  }
}
[root@VM_143_245_centos multi-node1]# ./ontology account list -v
1	TA86DZm9hVoqYmedZMVamWLvSCXQF942S6 (default)
	Label: ghost
	Signature algorithm: ECDSA
	Curve: P-256
	Key length: 256 bits
	Public key: 1202029ad0f87ad84b84b085b610475f5c4e409a7744c3732042a0498adf0a251dfde9
	Signature scheme: SHA256withECDSA

[root@VM_143_245_centos multi-node1]# ./ontology asset balance 1
BalanceOf:TA86DZm9hVoqYmedZMVamWLvSCXQF942S6
ONT:0
ONG:0
ONGApprove:0
[root@VM_143_245_centos multi-node1]#
