### ISSUE TITLE
Incorrectly book keepers key

### ISSUE THREAD

**Issue by Phoenix117** [ontio/ontology#239]
I have five nodes.Four of them have no problem,but only one has the problem "Incorrectly book keepers key" when I started all nodes.
And I found the public key is different from the other four nodes.

`root@bc154:/opt/go/src/github.com/ontio/ontology# ./ontology account add -d
Use default setting '-t ecdsa -b 256 -s SHA256withECDSA' 
	signature algorithm: ecdsa 
	curve: P-256 
	signature scheme: SHA256withECDSA 
Password:
Re-enter Password:

Index: 1
Label: 
Address: TA6RNsUTjHAbuEU6pM5eqa54Bcy2qJuasb
Public key: 020b70fef6abb397c4ef0f1114d24c623c4ea556e7e65dcd5aec8dae92057fa568
Signature scheme: SHA256withECDSA

Create account successfully.`

The public keys of the other four nodes is like '120202ce6a4122482372806ad0359e9aba5da0560053c97dd5543efc83325ef1098321'

**Comment by Phoenix117** [comment]
Does anyone know why?Thanks.

**Comment by panther142** [comment]
I don't know why it is happening (hopefully the core team can advise) but the public key should start with 1202. If you add 1202 at the start of that public key does it work without error?

**Comment by Phoenix117** [comment]
@panther142 No, it didn't work. The error is 'deserialize public key error. keyBuf:[3 105 159 113 19 217 58 54 177 38 104 184 31 15 3 184 5 215 49 85 10 19 237 163 98 175 175 51 34 13 171 81 188]: deserializing public key failed: unrecognized algorithm label'
It seems like we can't change the publickey.

**Comment by panther142** [comment]
That is odd. Can you delete the wallet for that node and create a new one to see if the same thing happens?

Is that node running the same version as the other nodes? Using ontology --version will tell you.

**Comment by Phoenix117** [comment]
@panther142 I'm sad.
`./ontology --version
ontology version 0.8.0`
The same version with the other nodes. 
I have tried delete wallet , delete project and rebuild it, and all of them didn't work.   0.0

**Comment by panther142** [comment]
What is in the config.json file for the node that doesn't work?

**Comment by Arbio5zt** [comment]
There seems all nodes you have are the same public key,  basicly you need to have the different keys deployed on the different node as the network id is marked by the public key, after that you need to have your config.json prepared for the local bookkeepers.
