### ISSUE TITLE
Issue with download

### ISSUE THREAD

**Issue by reachosen** [ontio/ontology#257]
When i try to download ontology.exe from https://github.com/ontio/ontology/releases
v0.82 for windows, it throws up an error.

"Forbidden" or "Failed - Forbidden"
This error means you don't have permission to download this file from the server.
To fix, go to the website where the file is hosted. Check if you need to sign in (or provide some other authentication).

**Comment by Arbio5zt** [comment]
Thanks for your message, we now hosting the files on the github, we may provide the aws cloudfront download link which have CDN in later time.
