### ISSUE TITLE
with -b cmd not show the ont amount this account have

### ISSUE THREAD

**Issue by jxzsxsp** [ontio/ontology#33]
[root@yueyue node1]# ./nodectl wallet -b
Password:
Wallet File: 'wallet.dat'
public key:    120203a8e3da743702d36abdf300b27925444a113b5737277c2ccb5a55363cff7aeec3
hex address:  01c8917e3383e9226430e6a6d0bbc7117f687948
base58 address:       TA8dwyxXvTXQFAxMefh3bqMidKs1czzP27

**Comment by laizy** [comment]
thanks for report, please use `./nodectl wallet -l -b` for the moment. A more full-featured cli is under development.
