### ISSUE TITLE
Typo NetworkMaigc on config.go file

### ISSUE THREAD

**Issue by jonatanblockchain** [ontio/ontology#377]
https://github.com/ontio/ontology/blob/fcee25788642b645f772585bf9c1ac105ce4aff8/common/config/config.go#L422

https://github.com/ontio/ontology/blob/fcee25788642b645f772585bf9c1ac105ce4aff8/common/config/config.go#L494

**Comment by Arbio5zt** [comment]
thanks, fixed by #489.
