### ISSUE TITLE
Is there any public testnet available?

### ISSUE THREAD

**Issue by northfoxz** [ontio/ontology#418]
Hi,
I've tried to launch the project but the default seed address of the network seems not to be working.
When will the testnet be available(or do I config the server in the wrong way?)
thanks!

**Comment by Arbio5zt** [comment]
yes you can use the ./ontology --networkid=2 the connect to polaris(testnet name). other cli function's specifications you can find in docs/specifications.

**Comment by jerry-sl** [comment]
./ontology --networkid=2   Keep report "Wait for minimum connection..." .

**Comment by Arbio5zt** [comment]
any updates i can help you?
