### ISSUE TITLE
does node deployment only work on "Single-host deployment configuration" (v1.0)

### ISSUE THREAD

**Issue by karenwang38** [ontio/ontology#497]
Hi,
I've tried to node deployment on Public test network Polaris "./ontology --networkid 2", but it didn't work as following (read connection error  EOF) : 

2018/07/01 17:13:58.787404 [INFO ] GID 172, peer 192.168.1.117:54856 connect with 52.221.232.201:20338 with tcp
2018/07/01 17:13:58.844318 [INFO ] GID 214, OnAddNode:10772187615756702585
2018/07/01 17:13:58.845722 [INFO ] GID 214, OnAddNode:16531974056532601916
2018/07/01 17:13:58.847156 [INFO ] GID 214, OnAddNode:13067852032383128053
2018/07/01 17:13:58.892431 [INFO ] GID 185, OnAddNode:6298344811280280623
2018/07/01 17:13:58.896282 [ERROR] GID 211, read connection error  EOF
2018/07/01 17:13:58.897618 [WARN ] GID 139, unknown status to received version 3
2018/07/01 17:13:58.898812 [ERROR] GID 199, read connection error  read tcp 192.168.1.117:54856->52.221.232.201:20338: use of closed network connection
2018/07/01 17:13:58.898885 [ERROR] GID 198, read connection error  EOF
2018/07/01 17:13:58.928939 [INFO ] GID 200, Node info:
2018/07/01 17:13:58.929583 [INFO ] GID 200,      syncState =  4
2018/07/01 17:13:58.931297 [INFO ] GID 200,      consState =  0
2018/07/01 17:13:58.929741 [INFO ] GID 215, Node info:
2018/07/01 17:13:58.931596 [INFO ] GID 217, Node info:
2018/07/01 17:13:58.937903 [INFO ] GID 200,      id =  16531974056532601916

Then it worked on Single-host deployment configuration "$ ./ontology --testmode --networkid 3"

2018/07/01 17:18:19.918539 [INFO ] GID 1, Rpc init success
2018/07/01 17:18:19.918733 [INFO ] GID 1, Restful init success
2018/07/01 17:18:19.919350 [INFO ] GID 1, Ws init success
2018/07/01 17:18:25.916644 [INFO ] GID 29, increment validator block height -1 != ledger block height 0
2018/07/01 17:18:25.918080 [INFO ] GID 29, current block height 0, increment validator block cache range: [0, 0)
2018/07/01 17:18:25.922694 [INFO ] GID 104, CurrentBlockHeight = 0
2018/07/01 17:18:25.924068 [INFO ] GID 29, solo actor receives block complete event. block height=1 txnum=0
2018/07/01 17:18:31.916578 [INFO ] GID 33, current block height 1, increment validator block cache range: [1, 2)
2018/07/01 17:18:31.921827 [INFO ] GID 33, solo actor receives block complete event. block height=2 txnum=0
2018/07/01 17:18:31.922764 [INFO ] GID 104, CurrentBlockHeight = 2
2018/07/01 17:18:37.916334 [INFO ] GID 117, current block height 2, increment validator block cache range: [1, 3)
2018/07/01 17:18:37.921537 [INFO ] GID 117, solo actor receives block complete event. block height=3 txnum=0

thanks!

**Comment by Arbio5zt** [comment]
by logs, there seems ok, as the blocks are continue.   this error logs is about connection, when bad network it will appear connection errors and will automatic recover when network is reachable.
