### ISSUE TITLE
我在本地testmode下发布智能合约，提示发布成功了，但是能命令行下查提示没有这个交易

### ISSUE THREAD

**Issue by jxzsxsp** [ontio/ontology#505]
发布合约代码：
OntSdk ontSdk = Base.getOntSdk();
            String code = "58c56b6a00527ac46a51527ac46a00c30548656c6c6f9c6416006a51c300c36a52527ac46a52c3650b006c756661006c756655c56b6a00527ac46a00c3680f4e656f2e52756e74696d652e4c6f6761516c7566";

            Account account = new Account(Helper.hexToBytes("7eeb1f37ce6802f0d459905306efcc0b0f520537110d7a08918659c9da12cbce"), SignatureScheme.SHA256WITHECDSA);

            Transaction tx = ontSdk.vm().makeDeployCodeTransaction(
                    code,
                    true,
                    "HelloWorld",
                    "v0.0.1",
                    "Sean.Xiao",
                    "jxzsxsp@qq.com",
                    "My first smart contract",
                    account.getAddressU160().toBase58(),
                    30000L,
                    0L);

            ontSdk.signTx(tx, new Account[][]{{account}});
            String txHex = Helper.toHexString(tx.toArray());
            System.out.println(txHex);
            Object result = ontSdk.getConnect().sendRawTransaction(txHex);
            System.out.println(result);

            System.out.println("txhash:" + tx.hash().toString());
            String txhash = tx.hash().toHexString();
            System.out.println("txhash:" + txhash);

返回结果：
00d0980fe805000000000000000030750000000000007958b9a3a0521cda7de973fb12b4431cc48d9bb65358c56b6a00527ac46a51527ac46a00c30548656c6c6f9c6416006a51c300c36a52527ac46a52c3650b006c756661006c756655c56b6a00527ac46a00c3680f4e656f2e52756e74696d652e4c6f6761516c7566010a48656c6c6f576f726c640676302e302e31095365616e2e5869616f0e6a787a737873704071712e636f6d174d7920666972737420736d61727420636f6e74726163740001424101cfeb3eef5414125a6d5985cb7873da223aea29d314d74451186fde08a9aa89efd93df1eb7b47e930f467089e51be56e990fd4e83a66bacfd97ec880b530b88b2232102aecca09cc3732b306990eb56cd0d5a7bb4d6bd81436311b10c5de756837fac4eac
POST url=http://localhost:20334/api/v1/transaction,{},{"Action":"sendrawtransaction","Version":"v1.0.0","Data":"00d0980fe805000000000000000030750000000000007958b9a3a0521cda7de973fb12b4431cc48d9bb65358c56b6a00527ac46a51527ac46a00c30548656c6c6f9c6416006a51c300c36a52527ac46a52c3650b006c756661006c756655c56b6a00527ac46a00c3680f4e656f2e52756e74696d652e4c6f6761516c7566010a48656c6c6f576f726c640676302e302e31095365616e2e5869616f0e6a787a737873704071712e636f6d174d7920666972737420736d61727420636f6e74726163740001424101cfeb3eef5414125a6d5985cb7873da223aea29d314d74451186fde08a9aa89efd93df1eb7b47e930f467089e51be56e990fd4e83a66bacfd97ec880b530b88b2232102aecca09cc3732b306990eb56cd0d5a7bb4d6bd81436311b10c5de756837fac4eac"}
true
txhash:510df28666b2912662965e57b11a9dec50a4ec265e08741b3301125249d92147
txhash:510df28666b2912662965e57b11a9dec50a4ec265e08741b3301125249d92147

命令行查询：
[root@736c4412a328 ontology]# ./ontology info tx 510df28666b2912662965e57b11a9dec50a4ec265e08741b3301125249d92147
error code:44001 desc:UNKNOWN TRANSACTION

**Comment by prettyCoders** [comment]
where can get ONT(mainnet)

**Comment by xizho10** [comment]
It is gaslimit and gasprice value not correct.

Check deploy your smartcontract need how much gaslimit first:

OntSdk ontSdk= OntSdk.getInstance();
ontSdk.setRpc(rpcUrl);
ontSdk.setDefaultConnect(wm.getRpc()); //use RPC for prepare execution 
Object result = ontSdk.getConnect().sendRawTransactionPreExec(txHex);
System.out.println(result);
//result:  {"State":1,"Gas":20020000}

than Fill the gaslimit with 20020000:

Transaction tx = ontSdk.vm().makeDeployCodeTransaction(
                code,
                true,
                "HelloWorld",
                "v0.0.1",
                "Sean.Xiao",
                "jxzsxsp@qq.com",
                "My first smart contract",
                account.getAddressU160().toBase58(),
                20020000L,   //**fix this** 
                500L);  //**fix this**  gasprice shoud more than 500, depend on node config

**Comment by xizho10** [comment]
mainnet:  http://dappnode1.ont.io     
or start local node, connect to seed node:  ./ontology --networkid 1 --rest

**Comment by jxzsxsp** [comment]
修改gasLimit后可以了
