### ISSUE TITLE
--networkid does not have an option for a privatenet

### ISSUE THREAD

**Issue by panther142** [ontio/ontology#506]
There is no networkid for a privatenet and setting it to anything higher than 3 defaults back to mainnet.

**Comment by gasby88** [comment]
If you want to startup a private network, you need  specify  a network id and config file. For example:     ./ontology --networkid=12 --config=config.json

**Comment by gasby88** [comment]
If don't specify a config file, ontology will use the main net config by default

**Comment by gasby88** [comment]
If you want to startup a private net, you should specify a network id an the config file of private net. For   example ./ontology --networkid=12 --config=config.json . If you don't specify the config file, Ontology will use the main net config by default.  After you do those, Ontology still connect to the main net, just delete the file "peers.recent" at the same  dir with ontology.

**Comment by panther142** [comment]
Thanks - close
