### ISSUE TITLE
在testmode下转账后不会生成ONG吗？

### ISSUE THREAD

**Issue by jxzsxsp** [ontio/ontology#508]

**Comment by xizho10** [comment]
Shoud be generate ong, clear Chain dir before start testmode, make sure your transfer is successful.

**Comment by jxzsxsp** [comment]
[root@736c4412a328 ontology]# ./ontology asset balance 1
BalanceOf:AVFAYhQqPFAoieDfHhqen4Ss7Q3fJM8SyP
  ONT:999981000
  ONG:0
[root@736c4412a328 ontology]# ./ontology asset balance 2
BalanceOf:AbZQBGn4zVFfPjvVZcXn9wzcw8Q6G9FTLF
  ONT:9000
  ONG:0
[root@736c4412a328 ontology]# ./ontology asset balance ASqVhSZW8CsyTHKb5jw2TbT1tKzFMQA4FX
BalanceOf:ASqVhSZW8CsyTHKb5jw2TbT1tKzFMQA4FX
  ONT:10000
  ONG:0
[root@736c4412a328 ontology]#

转账成功了，ONT有变化，ONG都为0

**Comment by Arbio5zt** [comment]
you need to use unboundong to get the ONGs

**Comment by jxzsxsp** [comment]
how to use unboundong

**Comment by Arbio5zt** [comment]
you can reference this [doc](https://github.com/ontio/ontology/blob/master/docs/specifications/cli_user_guide_CN.md#36-%E6%9F%A5%E7%9C%8B%E6%9C%AA%E8%A7%A3%E7%BB%91%E7%9A%84ong%E4%BD%99%E9%A2%9D)

**Comment by jxzsxsp** [comment]
好的，谢谢！
