### ISSUE TITLE
parse transaction from block

### ISSUE THREAD

**Issue by prettyCoders** [ontio/ontology#513]
Use java-sdk,I want parse transaction from block,get sender address、recipient address、amount、transaction hash.But not found!help me please!thanks.
Code：
Block block = ontSdk.getConnect().getBlock(9);
Transaction[] transactions=block.transactions;
System.out.println("block:"+block.json());
System.out.println("tx:"+transactions[0].json().toString());
Result:
{Nonce=1298299449, Payer=ASm7Uf6zae6JZ8WqYz1W9PSyvedAiznt5n, TxType=209, Version=0, Sigs=[Ljava.lang.Object;@43814d18, Attributes=[Ljava.lang.Object;@5c5a1b69, GasPrice=1, Payload={Code=00c66b147884833c8511f744b68fb4d69afcd037f042880d6a7cc814db2da7034bfd60fd1872bc169d8796d9f656a2ac6a7cc8566a7cc86c51c1087472616e736665721400000000000000000000000000000000000000010068164f6e746f6c6f67792e4e61746976652e496e766f6b65}, Hash=16eea36cf73247f8e680995e984339ab68afe3b372669f89be7068b603ba3293, GasLimit=30000}

**Comment by Arbio5zt** [comment]
there seems you need to query at [ontology-java-sdk](https://github.com/ontio/ontology-java-sdk)

**Comment by prettyCoders** [comment]
May be need deserialization,But i don`t know how to do it

**Comment by xizho10** [comment]
Don't need deserialization by yourself,  just get smartcontract event:  System.out.println(ontSdk.getConnect().getSmartCodeEvent("0795bbb043e81cd9cb9e95f215203379ccf967753fd9b1a281ec4b9200650a24"));

response:
{"GasConsumed":10000000,"Notify":[{"States":["transfer","AbT9aY8Ungm6FmbRXDdKyEBzKEm3U9HBfm","AdZFF1ottgfqNut5R64KZXsh3p6PMULfZD",1],"ContractAddress":"0100000000000000000000000000000000000000"},{"States":["transfer","Adj7W5Z2hTeKH7YwJsfMzLuwiD671mvJ6X","AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",10000000],"ContractAddress":"0200000000000000000000000000000000000000"}],"TxHash":"0795bbb043e81cd9cb9e95f215203379ccf967753fd9b1a281ec4b9200650a24","State":1}

Transfer content is in InvokeCode.Code:  System.out.println(Helper.toHexString(((InvokeCode)ontSdk.getConnect().getTransaction("0795bbb043e81cd9cb9e95f215203379ccf967753fd9b1a281ec4b9200650a24")).code));

**Comment by leeduckgo** [comment]
Get Transactions by one Request is more efficient, so is there any way to parse payload-code? I can code by myself but it's more reliable if there is any official code. :)

**Comment by albertschr** [comment]
@luodanwg

**Comment by leeduckgo** [comment]
@luodanwg @xizho10

**Comment by laizy** [comment]
the transaction execution may be failed, such as balance not enough. so it is not reliable.
