### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by shadowcz007** [ontio/ontology#527]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"mkdir /go/src/github.com: permission denied\"": unknown.
make: *** [docker/build/bin/ontology] Error 126

**Comment by qiluge** [comment]
Could you show me the `ll docker/build/bin/` command result ?

**Comment by Arbio5zt** [comment]
any updates i can help you?
