### ISSUE TITLE
Mainnet Block Not Sync after Height 9024

### ISSUE THREAD

**Issue by infinitystoneseng** [ontio/ontology#549]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
ontology version v1.0.1, master branch, latest SHA f3231afadaa6ba2d2b0ee3b68069685da7c88fbe

#### Does this issue reproduce with the latest release?
The issues is caused by c705b7004533c3ce45de5b555883a9a4d05f01cf

#### What operating system are you using (such as macOS, Linux and Windows)?
Linux.

#### What did you do?
After pulling the latest master and make all, we run
./ontology --networkid 1

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with the issue.
1) git checkout f3231afadaa6ba2d2b0ee3b68069685da7c88fbe
2) make all
3) ./ontology --networkid 1

#### What did you expect to see?
Block synchronized to the latest height

#### What did you see instead?
2018/07/16 23:30:15.040015 [INFO ] GID 31426, syncHeader request Height:9024
2018/07/16 23:30:16.071100 [INFO ] GID 31442, OnHeaderReceive Height:9024 - 9523
2018/07/16 23:30:16.071750 [ERROR] GID 31442, VerifyMultiSignature:invalid signature data,Bookkeepers:5,pubkey:7,heigh:9024
2018/07/16 23:30:16.071821 [ERROR] GID 31442, OnHeaderReceive AddHeaders error:verifyHeader error invalid signature data

#### Additional context
In c705b7004533c3ce45de5b555883a9a4d05f01cf, it changes the verifyHeader function of core/store/ledgerstore/ledger_store.go by adding VerifyMultiSignature function. However, the block 9024 uses an invalid scheme that is not defined in https://github.com/ontio/ontology-crypto/blob/master/signature/scheme.go. Therefore, the code throws error at Line 262 https://github.com/ontio/ontology-crypto/blob/master/signature/signature.go, and the block sync get stuck at the height 9024.

**Comment by Arbio5zt** [comment]
Thanks for asking, as the consensus node have not update to v1.0.1 when you do syncing,  you can try it again now, as we have finished the upgrading.

**Comment by Arbio5zt** [comment]
any updates i can help you?
