### ISSUE TITLE
代码活络起来呀

### ISSUE THREAD

**Issue by wangping0105** [ontio/ontology#56]
怎么提交这么不频繁，本体加油啊

**Comment by Ruining-Wu** [comment]
30买的很气

**Comment by Arbio5zt** [comment]
Thanks a lot for interesting in Ontology,  This is just a code library, you can join our discord ,telegram official chat room. We are also very welcome community contributors to participate in the development of ontology. Thanks for your message.

**Comment by wangping0105** [comment]
@Ruining-Wu 是啊，这几天都飞了，就本体不动
