### ISSUE TITLE
wagon/wasm: use upstream

### ISSUE THREAD

**Issue by sbinet** [ontio/ontology#567]
hi,

I noticed you've directly copied a bunch of [go-interpreter/wagon](https://github.com/go-interpreter/wagon) inside `ontology`:
- https://godoc.org/github.com/ontio/ontology/vm/wasmvm/wasm

I was wondering why you did that instead of just importing `wagon/wasm` (or vendoring it) ?
was there some shortcoming from `wagon/wasm` that you had to fix?

basically: what should I do on the `wagon/wasm` side to make your life easier?

**Comment by JasonZhouPW** [comment]
hi ，thank you for being interested in our project , wagon project is an excellent wasm project in golang, but  for a block chain system we need to interactive with low level apis and storages , and we need to support some more complex structs with in memories, it's not easy to just vendoring as a library. we have remained all your licenses  files and comments in source codes. If you have any concerns , please feel free to contact with us.

**Comment by sbinet** [comment]
no license concerns, really :)

I was just wondering what `wagon` could do to make it more useful as is (w/o local modifications.)
we've got already a few PRs from another blockchain related user (https://github.com/go-interpreter/wagon/pull/59, https://github.com/ethereum/go-ethereum/pull/16957), so we aren't against integrating some changes :)
