### ISSUE TITLE
Cannot check account balance?

### ISSUE THREAD

**Issue by karenwang38** [ontio/ontology#571]
ont2@ONT2:~/GoPath/src/github.com/ontio/ontology$ ./ontology account list
Index:1    Address:ARC4DTUtvX8u8ZySmSNet2UsonesUym3cS  Label: (default)
Index:2    Address:AHHDCGUgCiTZ3D8PbpTPiUj9a83TvbSfUn  Label:

ont2@ONT2:~/GoPath/src/github.com/ontio/ontology$ ./ontology asset balance 2
sendRpcRequest error:http post request:{"jsonrpc":"2.0","id":"cli","method":"getbalance","params":["AHHDCGUgCiTZ3D8PbpTPiUj9a83TvbSfUn"]} error:Post http://localhost:20336: dial tcp 127.0.0.1:20336: connect: connection refused

ont2@ONT2:~/GoPath/src/github.com/ontio/ontology$ ./ontology asset balance 1
sendRpcRequest error:http post request:{"jsonrpc":"2.0","id":"cli","method":"getbalance","params":["ARC4DTUtvX8u8ZySmSNet2UsonesUym3cS"]} error:Post http://localhost:20336: dial tcp 127.0.0.1:20336: connect: connection refused

thanks!

**Comment by zncrypto** [comment]
This might be because of port not accessible.

**Comment by karenwang38** [comment]
thanks!
