### ISSUE TITLE
[ERROR] GID 199, read connection error  EOF (on Mainnet sync node deployment)

### ISSUE THREAD

**Issue by karenwang38** [ontio/ontology#572]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
v1.0.1-15-gaeda

#### Does this issue reproduce with the latest release?
yes

#### What operating system are you using (such as macOS, Linux and Windows)?
Linux 

#### What did you do?
Mainnet sync node deployment.

Log:
2018/07/30 06:52:08.987652 [INFO ] GID 60, peer 10.0.1.4:45456 connect with 139.219.140.79:20338 with tcp
2018/07/30 06:52:09.017270 [INFO ] GID 195, Node info:
2018/07/30 06:52:09.017333 [INFO ] GID 195,      syncState =  4
2018/07/30 06:52:09.017373 [INFO ] GID 195,      consState =  0
2018/07/30 06:52:09.017411 [INFO ] GID 195,      id =  10563388247731019327
2018/07/30 06:52:09.017460 [INFO ] GID 195,      addr =  40.113.239.95:20338
2018/07/30 06:52:09.017518 [INFO ] GID 195,      cap =  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
2018/07/30 06:52:09.017565 [INFO ] GID 195,      version =  0
2018/07/30 06:52:09.017611 [INFO ] GID 195,      services =  2
2018/07/30 06:52:09.017666 [INFO ] GID 195,      syncPort =  20338
2018/07/30 06:52:09.017754 [INFO ] GID 195,      consPort =  0
2018/07/30 06:52:09.017797 [INFO ] GID 195,      relay =  true
2018/07/30 06:52:09.017863 [INFO ] GID 195,      height =  115583
2018/07/30 06:52:09.052584 [INFO ] GID 158, Node info:
2018/07/30 06:52:09.052636 [INFO ] GID 158,      syncState =  4
2018/07/30 06:52:09.052717 [INFO ] GID 158,      consState =  0
2018/07/30 06:52:09.052762 [INFO ] GID 158,      id =  3096506620776001001
2018/07/30 06:52:09.052817 [INFO ] GID 158,      addr =  104.45.19.210:20338
2018/07/30 06:52:09.052881 [INFO ] GID 158,      cap =  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
2018/07/30 06:52:09.052931 [INFO ] GID 158,      version =  0
2018/07/30 06:52:09.052982 [INFO ] GID 158,      services =  2
2018/07/30 06:52:09.053023 [INFO ] GID 158,      syncPort =  20338
2018/07/30 06:52:09.053127 [INFO ] GID 158,      consPort =  0
2018/07/30 06:52:09.053179 [INFO ] GID 158,      relay =  true
2018/07/30 06:52:09.053221 [INFO ] GID 158,      height =  115583
2018/07/30 06:52:09.077798 [INFO ] GID 134, peer 10.0.1.4:60646 connect with 52.198.155.118:20338 with tcp
2018/07/30 06:52:09.078810 [INFO ] GID 138, peer 10.0.1.4:34548 connect with 52.197.238.245:20338 with tcp
2018/07/30 06:52:09.081132 [INFO ] GID 136, peer 10.0.1.4:46728 connect with 54.250.241.22:20338 with tcp
2018/07/30 06:52:09.086911 [INFO ] GID 140, peer 10.0.1.4:43918 connect with 18.182.239.242:20338 with tcp
2018/07/30 06:52:09.096549 [INFO ] GID 183, OnAddNode:8015415082370809860
2018/07/30 06:52:09.117447 [INFO ] GID 139, peer 10.0.1.4:52848 connect with 52.231.153.200:20338 with tcp
2018/07/30 06:52:09.147332 [INFO ] GID 45, peer 10.0.1.4:40826 connect with 139.219.129.26:20338 with tcp
2018/07/30 06:52:09.227654 [INFO ] GID 48, peer 10.0.1.4:59288 connect with 118.178.129.13:20338 with tcp
2018/07/30 06:52:09.238090 [INFO ] GID 187, OnAddNode:11184694042835741623
2018/07/30 06:52:09.257785 [ERROR] GID 199, read connection error  EOF
2018/07/30 06:52:09.260169 [ERROR] GID 200, read connection error  EOF
2018/07/30 06:52:09.264759 [ERROR] GID 201, read connection error  read tcp 10.0.1.4:46728->54.250.241.22:20338: readnection reset by peer
2018/07/30 06:52:09.270373 [INFO ] GID 210, OnAddNode:7903060087312080697
2018/07/30 06:52:09.274500 [INFO ] GID 226, Node info:
2018/07/30 06:52:09.274570 [INFO ] GID 226,      syncState =  4
2018/07/30 06:52:09.274607 [INFO ] GID 226,      consState =  0
2018/07/30 06:52:09.274647 [INFO ] GID 226,      id =  8015415082370809860
2018/07/30 06:52:09.274720 [INFO ] GID 226,      addr =  13.78.34.73:20338
2018/07/30 06:52:09.274777 [INFO ] GID 226,      cap =  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
2018/07/30 06:52:09.274815 [INFO ] GID 226,      version =  0
2018/07/30 06:52:09.274854 [INFO ] GID 226,      services =  2
2018/07/30 06:52:09.274882 [INFO ] GID 226,      syncPort =  20338
2018/07/30 06:52:09.274907 [INFO ] GID 226,      consPort =  0
2018/07/30 06:52:09.274939 [INFO ] GID 226,      relay =  true
2018/07/30 06:52:09.274975 [INFO ] GID 226,      height =  115583
2018/07/30 06:52:09.337567 [INFO ] GID 190, OnAddNode:17658260025267060154
2018/07/30 06:52:09.397652 [ERROR] GID 203, read connection error  EOF

#### What did you expect to see?
connection not error

#### What did you see instead?
2018/07/30 06:52:09.257785 [ERROR] GID 199, read connection error  EOF
2018/07/30 06:52:09.260169 [ERROR] GID 200, read connection error  EOF
2018/07/30 06:52:09.264759 [ERROR] GID 201, read connection error  read tcp 10.0.1.4:46728->54.250.241.22:20338: readnection reset by peer

2018/07/30 06:52:09.397652 [ERROR] GID 203, read connection error  EOF

**Comment by Arbio5zt** [comment]
Sorry for confusing you about the error message,  as some nodes are LAN, such as the IP displayed is 10.0.0.1/192.168.1.1, so it is the reason of connection error. but it will not crash the node, we will change it to the low log level, thanks for your post.

**Comment by karenwang38** [comment]
thanks for your detailed explanation.

**Comment by BooniesFX** [comment]
Most debug output will be changed to low level, and more detail info added in debug level for develop purpose.see https://github.com/ontio/ontology/pull/521
