### ISSUE TITLE
Can check ONT balance on Mainnet ?

### ISSUE THREAD

**Issue by karenwang38** [ontio/ontology#573]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
v1.0.1-15-gaeda

#### Does this issue reproduce with the latest release?
yes

#### What operating system are you using (such as macOS, Linux and Windows)?
Linux

#### What did you do?
I created a wallet on iOS "ONTO" and deposited ont.
I  checked ont balance on mainnet and the number of ont always 0.
So I want to know if I can check ont balance on mainnet?

ont2@ONT2:~/GoPath/src/github.com/ontio/ontology_v1.0.1-15-gaeda$ ./ontology asset balance AKSKgme9wEyUvkxJ7yePtVg6E8s6zxG7dG
BalanceOf:AKSKgme9wEyUvkxJ7yePtVg6E8s6zxG7dG
  ONT:0
  ONG:0

#### What did you expect to see?
ont balance is correct.

#### What did you see instead?
ont balance is zero.

**Comment by Arbio5zt** [comment]
I see you address have ont and ong ,https://explorer.ont.io/address/AKSKgme9wEyUvkxJ7yePtVg6E8s6zxG7dG/10/1,
so if you have solve the problem?

**Comment by karenwang38** [comment]
yes, it can work.
thank you very much.
