### ISSUE TITLE
Cannot build docker image

### ISSUE THREAD

**Issue by jinge1936** [ontio/ontology#577]
The source root does not have config.json file, so when we make docker image, the shell will throw errors. 

I checked the histories, it seems the config.json files are removed right now. Would you please update the makefile accordingly？

**Comment by jinge1936** [comment]
Anyone who could look into this issue?

**Comment by Arbio5zt** [comment]
sorry for the late response, @qiluge is working on this issue.

**Comment by qiluge** [comment]
The problem has been resolved, please update to latest version, thx.

**Comment by Arbio5zt** [comment]
could you please confirm it @jinge1936 ,thanks.

**Comment by KaiserKarel** [comment]
still getting 
```
Status: Downloaded newer image for golang:1.9.5-stretch
container_linux.go:262: starting container process caused "chdir to cwd (\"/go/src/github.com/ontio/ontology\") set in config.json failed: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "chdir to cwd (\"/go/src/github.com/ontio/ontology\") set in config.json failed: no such file or directory".
```
on master

**Comment by qiluge** [comment]
1. clean older docker container and image;
![image](https://user-images.githubusercontent.com/19525062/43873822-e31c8e5e-9bba-11e8-8b91-9c32b502ede8.png)

2. update code to latest in the master branch;
![image](https://user-images.githubusercontent.com/19525062/43873845-022b3b10-9bbb-11e8-8556-03419dd2333d.png)

3. `make docker` in the root dir of ontology code;
![image](https://user-images.githubusercontent.com/19525062/43873890-345007f6-9bbb-11e8-98f1-a54c3f960cee.png)

4. `docker run -ti ontio/ontology --networkid 1`;
![image](https://user-images.githubusercontent.com/19525062/43873909-4bb7fb38-9bbb-11e8-9602-3f24b03a8924.png)

**Comment by qiluge** [comment]
Please refer to these steps, @KaiserKarel .

**Comment by Honglei-Cong** [comment]
I tried 'make docker', looks good.

close the issue?

**Comment by inertia186** [comment]
`make docker` fails

```
Building ontology in docker
Unable to find image 'golang:1.9.5-stretch' locally
1.9.5-stretch: Pulling from library/golang
cc1a78bfd46b: Pull complete 
53c14872d997: Pull complete 
99ae159b9cae: Pull complete 
66cbf2b79699: Pull complete 
a16f46d95485: Pull complete 
26416dc48904: Pull complete 
38b0dec0e83c: Pull complete 
609f54e21f6e: Pull complete 
Digest: sha256:e30310588adf197f3af576da13fb5b8768566d9adaa377a6455bff870977b943
Status: Downloaded newer image for golang:1.9.5-stretch
stat main.go: no such file or directory
Makefile:74: recipe for target 'docker/build/bin/ontology' failed
make: *** [docker/build/bin/ontology] Error 1
```
