### ISSUE TITLE
[question] Why do we use params with such format: `--maxconninboundforsingleip`

### ISSUE THREAD

**Issue by freewind** [ontio/ontology#589]
It's really hard to read: `--maxconninboundforsingleip`, why not `--max-conn-in-bound-for-single-ip`? Is there any reason for this?

**Comment by Arbio5zt** [comment]
thanks for proposal. The meaning of cmd would be list on the description, so the cmd is design to easy to input. so have no uppercase or '-' in all the cmds. but this is a good question for why this cmd is so long. This could be optimization in the next version.

**Comment by freewind** [comment]
Thanks for response. You're right, easily inputing may be a good reason for command line params, if the param is not so long. 

I think it's we can use such rules:

- if the params contains only two words, use none-`-` type: e.g. `nodeport`, `consensusport`, `networdid`
- if more than 2, use `-`: `max-conn-in-bound-for-single-ip`

This is just my opinion, I'm sure you will find better solutions

**Comment by Arbio5zt** [comment]
thanks, we will consider about it.

**Comment by Arbio5zt** [comment]
will improve by #612

**Comment by Arbio5zt** [comment]
released in v1.0.3
