### ISSUE TITLE
难以同步主网。error sending messge to peer node | sync link invalid | connect failed i/o timeout

### ISSUE THREAD

**Issue by junhuoku007** [ontio/ontology#591]
#### What version of ontology are you using (`ontology --version`)?
ontology-linux-amd64 of ontology version v1.0.1

#### What operating system are you using (such as macOS, Linux and Windows)?
Centos7 minimal
服务器是腾讯云（成都区域）

#### What did you do?

直接连接主网
./ontology --networkid 1

#### What did you expect to see?

能正常同步区块

#### What did you see instead?

不正常的同步区块
2018/08/07 19:54:45.708463 [ERROR] GID 105077, read connection error  EOF
2018/08/07 19:54:48.461635 [INFO ] GID 117489, checkTimeout sync headers:5001 timeout after:2 s Times:68
2018/08/07 19:54:49.467973 [INFO ] GID 311, CurrentBlockHeight = 1422
2018/08/07 19:54:49.782855 [INFO ] GID 115338, connect ip address: 54.95.68.0:20338
2018/08/07 19:54:49.782920 [INFO ] GID 115338, connect ip address: 54.66.154.140:20338
2018/08/07 19:54:49.784685 [INFO ] GID 115338, connect ip address: 47.52.196.117:30164
2018/08/07 19:54:49.784722 [INFO ] GID 115338, connect ip address: 54.169.109.231:20338
2018/08/07 19:54:49.784750 [INFO ] GID 115338, connect ip address: 107.155.56.28:20338
2018/08/07 19:54:49.784781 [INFO ] GID 115338, connect ip address: 13.125.110.186:20338
2018/08/07 19:54:49.784809 [INFO ] GID 115338, connect ip address: 47.91.248.37:30164
2018/08/07 19:54:49.784839 [INFO ] GID 115338, connect ip address: 13.114.212.150:20338
2018/08/07 19:54:49.787651 [INFO ] GID 106932, Node info:
2018/08/07 19:54:49.787690 [INFO ] GID 106932, 	 syncState =  4
2018/08/07 19:54:49.787718 [INFO ] GID 106932, 	 consState =  0
2018/08/07 19:54:49.787743 [INFO ] GID 106932, 	 id =  1480515156475380131
2018/08/07 19:54:49.787768 [INFO ] GID 106932, 	 addr =  13.114.212.150:43604
2018/08/07 19:54:49.787792 [INFO ] GID 106932, 	 cap =  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2018/08/07 19:54:49.787811 [INFO ] GID 106932, 	 version =  0
2018/08/07 19:54:49.787827 [INFO ] GID 106932, 	 services =  2
2018/08/07 19:54:49.787842 [INFO ] GID 106932, 	 syncPort =  20338
2018/08/07 19:54:49.787856 [INFO ] GID 106932, 	 consPort =  0
2018/08/07 19:54:49.787871 [INFO ] GID 106932, 	 relay =  true
2018/08/07 19:54:49.787885 [INFO ] GID 106932, 	 height =  144318
2018/08/07 19:54:51.454748 [INFO ] GID 35, remote sync node connect with  45.193.17.204:38668 10.139.157.225:20338
2018/08/07 19:54:51.461263 [INFO ] GID 118609, checkTimeout sync headers:5001 timeout after:2 s Times:69
2018/08/07 19:54:54.461459 [INFO ] GID 120801, checkTimeout sync headers:5001 timeout after:2 s Times:70
2018/08/07 19:54:54.793969 [ERROR] GID 6791, error sending messge to peer node  write tcp 10.139.157.225:20338->61.135.172.70:48159: i/o timeout
2018/08/07 19:54:54.794388 [ERROR] GID 5855, read connection error  read tcp 10.139.157.225:20338->61.135.172.70:48159: use of closed network connection
2018/08/07 19:54:54.794623 [ERROR] GID 107027, sync link invalid
2018/08/07 19:54:54.795942 [ERROR] GID 107681, sync link invalid
2018/08/07 19:54:54.796475 [ERROR] GID 108159, sync link invalid
2018/08/07 19:54:54.796689 [ERROR] GID 108190, sync link invalid
2018/08/07 19:54:54.800590 [ERROR] GID 109861, sync link invalid
2018/08/07 19:54:55.467870 [INFO ] GID 311, CurrentBlockHeight = 1422
2018/08/07 19:54:55.784677 [ERROR] GID 118181, connect failed:  dial tcp 54.95.68.0:20338: i/o timeout
2018/08/07 19:54:55.784790 [ERROR] GID 118182, connect failed:  dial tcp 54.66.154.140:20338: i/o timeout
2018/08/07 19:54:55.785044 [ERROR] GID 118256, connect failed:  dial tcp 13.114.212.150:20338: i/o timeout
2018/08/07 19:54:55.786166 [ERROR] GID 118251, connect failed:  dial tcp 47.52.196.117:30164: i/o timeout
2018/08/07 19:54:55.786257 [ERROR] GID 118252, connect failed:  dial tcp 54.169.109.231:20338: i/o timeout
2018/08/07 19:54:55.786317 [ERROR] GID 118253, connect failed:  dial tcp 107.155.56.28:20338: i/o timeout
2018/08/07 19:54:55.786383 [ERROR] GID 118254, connect failed:  dial tcp 13.125.110.186:20338: i/o timeout
2018/08/07 19:54:55.786456 [ERROR] GID 118255, connect failed:  dial tcp 47.91.248.37:30164: i/o timeout
2018/08/07 19:54:57.462007 [INFO ] GID 123259, checkTimeout sync headers:5001 timeout after:2 s Times:71
2018/08/07 19:54:58.110322 [INFO ] GID 35, remote sync node connect with  61.135.172.70:56802 10.139.157.225:20338
2018/08/07 19:54:59.804011 [ERROR] GID 6791, error sending messge to peer node  write tcp 10.139.157.225:20338->13.114.212.150:59905: i/o timeout
2018/08/07 19:54:59.804436 [ERROR] GID 74764, read connection error  read tcp 10.139.157.225:20338->13.114.212.150:59905: use of closed network connection
2018/08/07 19:54:59.805372 [ERROR] GID 110514, sync link invalid
2018/08/07 19:54:59.805435 [ERROR] GID 110515, sync link invalid
2018/08/07 19:54:59.805898 [ERROR] GID 111490, sync link invalid
2018/08/07 19:54:59.806174 [ERROR] GID 112206, sync link invalid
2018/08/07 19:54:59.806314 [ERROR] GID 112311, sync link invalid
2018/08/07 19:54:59.806562 [ERROR] GID 112468, sync link invalid
2018/08/07 19:54:59.806600 [ERROR] GID 112469, sync link invalid
2018/08/07 19:54:59.806728 [ERROR] GID 123868, P2PServer send to a not ESTABLISH peer 10079957436725313554
2018/08/07 19:54:59.822951 [ERROR] GID 113381, sync link invalid
2018/08/07 19:54:59.827588 [ERROR] GID 114117, sync link invalid
2018/08/07 19:55:00.461276 [INFO ] GID 124292, checkTimeout sync headers:5001 timeout after:2 s Times:72
2018/08/07 19:55:01.467915 [INFO ] GID 311, CurrentBlockHeight = 1422
2018/08/07 19:55:03.461258 [INFO ] GID 126605, checkTimeout sync headers:5001 timeout after:2 s Times:73
2018/08/07 19:55:04.831229 [ERROR] GID 6791, error sending messge to peer node  write tcp 10.139.157.225:20338->13.114.245.142:62041: i/o timeout
2018/08/07 19:55:04.831561 [ERROR] GID 78601, read connection error  read tcp 10.139.157.225:20338->13.114.245.142:62041: use of closed network connection
2018/08/07 19:55:04.832235 [ERROR] GID 114740, sync link invalid
2018/08/07 19:55:04.832282 [ERROR] GID 114757, sync link invalid
2018/08/07 19:55:04.832384 [ERROR] GID 115018, sync link invalid
2018/08/07 19:55:04.832731 [ERROR] GID 115339, sync link invalid
2018/08/07 19:55:04.832825 [ERROR] GID 115380, sync link invalid
2018/08/07 19:55:04.833024 [ERROR] GID 115582, sync link invalid
2018/08/07 19:55:04.833146 [ERROR] GID 127017, P2PServer send to a not ESTABLISH peer 7903060087312080697
2018/08/07 19:55:04.833204 [ERROR] GID 115627, sync link invalid
2018/08/07 19:55:04.833688 [ERROR] GID 116406, sync link invalid
2018/08/07 19:55:04.833736 [ERROR] GID 116505, sync link invalid
2018/08/07 19:55:04.836592 [ERROR] GID 117512, sync link invalid
2018/08/07 19:55:04.837710 [INFO ] GID 40,  try reconnect 18.182.239.242:20338
2018/08/07 19:55:04.837775 [INFO ] GID 40,  try reconnect 45.193.17.204:20338
2018/08/07 19:55:04.837833 [INFO ] GID 40, Try to reconnect peer, peer addr is  45.193.17.204:20338
2018/08/07 19:55:04.839491 [ERROR] GID 118080, sync link invalid
2018/08/07 19:55:06.131998 [INFO ] GID 40, Back off time`s up, start connect node
2018/08/07 19:55:06.461438 [INFO ] GID 128313, checkTimeout sync headers:5001 timeout after:2 s Times:74
2018/08/07 19:55:07.468302 [INFO ] GID 311, CurrentBlockHeight = 1422
2018/08/07 19:55:07.940109 [INFO ] GID 35, remote sync node connect with  13.114.245.142:61097 10.139.157.225:20338
2018/08/07 19:55:09.461264 [INFO ] GID 130572, checkTimeout sync headers:5001 timeout after:2 s Times:75

**Comment by junhuoku007** [comment]
最后 被Killed
2018/08/07 20:08:40.039943 [INFO ] GID 50, Back off time`s up, start connect node
2018/08/07 20:08:41.377163 [ERROR] GID 3657, error sending messge to peer node  write tcp 10.139.157.225:34028->18.182.239.242:20338: i/o timeout
2018/08/07 20:08:41.377834 [ERROR] GID 103517, read connection error  read tcp 10.139.157.225:34028->18.182.239.242:20338: use of closed network connection
2018/08/07 20:08:41.377915 [INFO ] GID 124920, connect ip address: 104.45.19.210:20338
2018/08/07 20:08:41.377946 [INFO ] GID 124920, connect ip address: 35.236.22.169:20338
2018/08/07 20:08:41.377974 [INFO ] GID 124920, connect ip address: 104.198.80.113:20338
2018/08/07 20:08:41.379074 [INFO ] GID 124920, connect ip address: 47.91.248.37:30164
2018/08/07 20:08:41.379107 [INFO ] GID 124920, connect ip address: 47.90.29.31:20338
2018/08/07 20:08:41.379129 [INFO ] GID 124920, connect ip address: 59.110.223.44:20338
2018/08/07 20:08:41.379146 [INFO ] GID 124920, connect ip address: 47.52.114.209:20338
2018/08/07 20:08:41.379161 [INFO ] GID 124920, connect ip address: 35.190.233.96:20338
2018/08/07 20:08:41.379175 [INFO ] GID 124920, connect ip address: 218.88.22.46:20338
2018/08/07 20:08:41.389091 [INFO ] GID 124891, Node info:
2018/08/07 20:08:41.389143 [INFO ] GID 124891, 	 syncState =  4
2018/08/07 20:08:41.389159 [INFO ] GID 124891, 	 consState =  0
2018/08/07 20:08:41.389175 [INFO ] GID 124891, 	 id =  991760955010426002
2018/08/07 20:08:41.389190 [INFO ] GID 124891, 	 addr =  104.198.80.113:37898
2018/08/07 20:08:41.389212 [INFO ] GID 124891, 	 cap =  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2018/08/07 20:08:41.389229 [INFO ] GID 124891, 	 version =  0
2018/08/07 20:08:41.389243 [INFO ] GID 124891, 	 services =  2
2018/08/07 20:08:41.389259 [INFO ] GID 124891, 	 syncPort =  20338
2018/08/07 20:08:41.389274 [INFO ] GID 124891, 	 consPort =  0
2018/08/07 20:08:41.389295 [INFO ] GID 124891, 	 relay =  true
2018/08/07 20:08:41.389322 [INFO ] GID 124891, 	 height =  144350
2018/08/07 20:08:41.399454 [ERROR] GID 127120, connect failed:  dial tcp 218.88.22.46:20338: getsockopt: connection refused
2018/08/07 20:08:41.716771 [INFO ] GID 127062, peer 10.139.157.225:52620 connect with 104.45.19.210:20338 with tcp
2018/08/07 20:08:41.981688 [ERROR] GID 125409, sync link invalid
2018/08/07 20:08:42.799967 [INFO ] GID 127492, checkTimeout sync headers:3423 timeout after:2 s Times:102
2018/08/07 20:08:42.806939 [INFO ] GID 916, CurrentBlockHeight = 1941
2018/08/07 20:08:45.799589 [INFO ] GID 128172, checkTimeout sync headers:3423 timeout after:2 s Times:103
2018/08/07 20:08:46.985666 [ERROR] GID 3657, error sending messge to peer node  write tcp 10.139.157.225:20338->35.235.73.4:48586: i/o timeout
2018/08/07 20:08:46.985820 [ERROR] GID 126081, sync link invalid
2018/08/07 20:08:46.985878 [ERROR] GID 14419, read connection error  read tcp 10.139.157.225:20338->35.235.73.4:48586: use of closed network connection
2018/08/07 20:08:46.987106 [ERROR] GID 126775, sync link invalid
2018/08/07 20:08:47.378430 [ERROR] GID 50, connect failed:  dial tcp 104.198.80.113:20338: i/o timeout
2018/08/07 20:08:47.378492 [INFO ] GID 50, Try to reconnect peer, peer addr is  45.193.17.204:20338
2018/08/07 20:08:47.379091 [ERROR] GID 127063, connect failed:  dial tcp 35.236.22.169:20338: i/o timeout
2018/08/07 20:08:47.379141 [ERROR] GID 127064, connect failed:  dial tcp 104.198.80.113:20338: i/o timeout
2018/08/07 20:08:47.380145 [ERROR] GID 127115, connect failed:  dial tcp 47.91.248.37:30164: i/o timeout
2018/08/07 20:08:47.380199 [ERROR] GID 127116, connect failed:  dial tcp 47.90.29.31:20338: i/o timeout
2018/08/07 20:08:47.380233 [ERROR] GID 127117, connect failed:  dial tcp 59.110.223.44:20338: i/o timeout
2018/08/07 20:08:47.380301 [ERROR] GID 127118, connect failed:  dial tcp 47.52.114.209:20338: i/o timeout
2018/08/07 20:08:47.380367 [ERROR] GID 127119, connect failed:  dial tcp 35.190.233.96:20338: i/o timeout
2018/08/07 20:08:48.799612 [INFO ] GID 128893, checkTimeout sync headers:3423 timeout after:2 s Times:104
2018/08/07 20:08:48.806901 [INFO ] GID 916, CurrentBlockHeight = 1941
2018/08/07 20:08:49.255875 [INFO ] GID 35, remote sync node connect with  18.182.239.242:50874 10.139.157.225:20338
Killed

**Comment by Arbio5zt** [comment]
Thanks, we have optimize the sync by #554  could please retest it by master branch.

**Comment by junhuoku007** [comment]
Thanks! Please release newer executable program as soon.
