### ISSUE TITLE
Can not startup with genesis config_vbft.json

### ISSUE THREAD

**Issue by lcgogo** [ontio/ontology#594]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
root@ubuntu-xenial:/vagrant/ont-build# ./ontology --version
ontology version v1.0.1-23-g966d

#### Does this issue reproduce with the latest release?
Yes

#### What operating system are you using (such as macOS, Linux and Windows)?
root@ubuntu-xenial:/vagrant/ont-build# uname -a
Linux ubuntu-xenial 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### What did you do?
root@ubuntu-xenial:/vagrant/ont-build# ./ontology --config /vagrant/ont-build/config_vbft.json
2018/08/08 11:23:31.085901 [INFO ] GID 1, Load genesis config:/vagrant/ont-build/config_vbft.json
2018/08/08 11:23:31.086605 [ERROR] GID 1, initConfig error:setGenesis error:VBFT config error initConfig. MinInitStake must >= 10000!

I can run ontology with dbft.json
root@ubuntu-xenial:/vagrant/ont-build# ./ontology --config /vagrant/ont-build/config_dbft.json
2018/08/08 11:22:50.745779 [INFO ] GID 1, Load genesis config:/vagrant/ont-build/config_dbft.json
2018/08/08 11:22:50.746732 [INFO ] GID 1, Config init success
2018/08/08 11:22:50.790171 [INFO ] GID 1, deploy contract address:0239dcf9b4a46f15c5f23f20d52fac916a0bac0d

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

#### What did you expect to see?
ontology runs

#### What did you see instead?
2018/08/08 11:23:31.086605 [ERROR] GID 1, initConfig error:setGenesis error:VBFT config error initConfig. MinInitStake must >= 10000!

#### Additional context

root@ubuntu-xenial:/vagrant/ont-build# cat config_vbft.json
`
{
  "SeedList": [
    "192.168.0.1:20338"
  ],
  "ConsensusType":"vbft",
  "VBFT":{
    "n":7,
    "c":2,
    "k":7,
    "l":112,
    "block_msg_delay":10000,
    "hash_msg_delay":10000,
    "peer_handshake_timeout":10,
    "max_block_change_view":1000,
    "vrf_value":"1c9810aa9822e511d5804a9c4db9dd08497c31087b0daafa34d768a3253441fa20515e2f30f81741102af0ca3cefc4818fef16adb825fbaa8cad78647f3afb590e",
    "vrf_proof":"c57741f934042cb8d8b087b44b161db56fc3ffd4ffb675d36cd09f83935be853d8729f3f5298d12d6fd28d45dde515a4b9d7f67682d182ba5118abf451ff1988",
    "peers":[
      {
        "index":1,
        "peerPubkey":"1202028541d32f3b09180b00affe67a40516846c16663ccb916fd2db8106619f087527",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":1000
      },
      {
        "index":2,
        "peerPubkey":"120202dfb161f757921898ec2e30e3618d5c6646d993153b89312bac36d7688912c0ce",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":2000
      },
      {
        "index":3,
        "peerPubkey":"1202039dab38326268fe82fb7967fe2e7f5f6eaced6ec711148a66fbb8480c321c19dd",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":3000
      },
      {
        "index":4,
        "peerPubkey":"12020384f2729bc5d9b14dcbf17aba108261dc7ad867127e413d3c8bfb4731739687b3",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":4000
      },
      {
        "index":5,
        "peerPubkey":"120203362f99284daa9f581fab596516f75475fc61a5f80de0e268a68430dc7589859c",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":3000
      },
      {
        "index":6,
        "peerPubkey":"120203db6e37a2d897f2d61b42dcd478323a8a20c3444af4ee29653849f38d0bdb67f4",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":2000
      },
      {
        "index":7,
        "peerPubkey":"12020298fe9f22e9df64f6bfcc1c2a14418846cffdbbf510d261bbc3fa6d47073df9a2",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":1000
      }
    ]
  }
}
`

**Comment by qiluge** [comment]
'initPos' config should >= 10000 of each peer.

**Comment by lcgogo** [comment]
@qiluge Same printout
root@ubuntu-xenial:/vagrant/ont-build# ./ontology --config /vagrant/ont-build/config_vbft.json
2018/08/09 02:15:38.932789 [INFO ] GID 1, Load genesis config:/vagrant/ont-build/config_vbft.json
2018/08/09 02:15:38.933598 [ERROR] GID 1, initConfig error:setGenesis error:VBFT config error initConfig. MinInitStake must >= 10000!

I set all the initPos of each peer to 20000


root@ubuntu-xenial:/vagrant/ont-build# cat config_vbft.json
`
{
  "SeedList": [
    "192.168.0.1:20338"
  ],
  "ConsensusType":"vbft",
  "VBFT":{
    "n":7,
    "c":2,
    "k":7,
    "l":112,
    "block_msg_delay":10000,
    "hash_msg_delay":10000,
    "peer_handshake_timeout":10,
    "max_block_change_view":1000,
    "vrf_value":"1c9810aa9822e511d5804a9c4db9dd08497c31087b0daafa34d768a3253441fa20515e2f30f81741102af0ca3cefc4818fef16adb825fbaa8cad78647f3afb590e",
    "vrf_proof":"c57741f934042cb8d8b087b44b161db56fc3ffd4ffb675d36cd09f83935be853d8729f3f5298d12d6fd28d45dde515a4b9d7f67682d182ba5118abf451ff1988",
    "peers":[
      {
        "index":1,
        "peerPubkey":"1202028541d32f3b09180b00affe67a40516846c16663ccb916fd2db8106619f087527",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":20000
      },
      {
        "index":2,
        "peerPubkey":"120202dfb161f757921898ec2e30e3618d5c6646d993153b89312bac36d7688912c0ce",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":20000
      },
      {
        "index":3,
        "peerPubkey":"1202039dab38326268fe82fb7967fe2e7f5f6eaced6ec711148a66fbb8480c321c19dd",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":20000
      },
      {
        "index":4,
        "peerPubkey":"12020384f2729bc5d9b14dcbf17aba108261dc7ad867127e413d3c8bfb4731739687b3",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":20000
      },
      {
        "index":5,
        "peerPubkey":"120203362f99284daa9f581fab596516f75475fc61a5f80de0e268a68430dc7589859c",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":20000
      },
      {
        "index":6,
        "peerPubkey":"120203db6e37a2d897f2d61b42dcd478323a8a20c3444af4ee29653849f38d0bdb67f4",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":20000
      },
      {
        "index":7,
        "peerPubkey":"12020298fe9f22e9df64f6bfcc1c2a14418846cffdbbf510d261bbc3fa6d47073df9a2",
        "address":"TA9TVuR4Ynn4VotfpExY5SaEy8a99obFPr",
        "initPos":20000
      }
    ]
  }
}
`

**Comment by xiemylogos** [comment]
I think you should set MinInitStake in your config_vbft.json. reference flie ontology/common/config/config.go in 199 lines.

**Comment by lcgogo** [comment]
@xiemylogos  Thanks but I think the MinInitStake should be     "min_init_stake": 100000,    in json.

However, I met another error as below:
root@ubuntu-xenial:/vagrant/ont-build# ./ontology --config /vagrant/ont-build/config_vbft.json
2018/08/09 03:44:04.727351 [INFO ] GID 1, Load genesis config:/vagrant/ont-build/config_vbft.json
2018/08/09 03:44:04.744963 [ERROR] GID 1, initConfig error:setGenesis error:VBFT config error common.AddressFromBase58, address format error!: wrong encoded address

BTW:
I got the json config from below link and remove the comments. Is it out of date?
https://github.com/ontio/ontology/blob/master/docs/specifications/cli_user_guide.md#1211-vbft-configuration-file

**Comment by lcgogo** [comment]
I use another json from
https://github.com/ontio/ontology/blob/master/docs/specifications/config-vbft.json
and now the start up is ok.

**Comment by Arbio5zt** [comment]
thanks for reporting, we have update the docs.
