### ISSUE TITLE
在测试网Polaris上部署python版合约报错:%!(EXTRA errors.ontError=[NeoVmService] service system call error!: [SystemCall] service not support: Neo.Storage.GetContext)

### ISSUE THREAD

**Issue by zouxyan** [ontio/ontology#598]
ontology version v1.0.1
centos7

- ####What did you do?
在smartx上编译了如下代码：
```
from boa.interop.Neo.Runtime import Log, Notify
from boa.interop.Neo.Storage import Get, Put, GetContext

def Main():
    context = GetContext()

    # This is the storage key we use in this example
    item_key = 'test-storage-key'

    # Try to get a value for this key from storage
    item_value = Get(context, item_key)
    msg = ["Value read from storage:", item_value]
    Notify(msg)

    if len(item_value) == 0:
        Notify("Storage key not yet set. Setting to 1")
        item_value = 1

    else:
        Notify("Storage key already set. Incrementing by 1")
        item_value += 1

    # Store the new value
    Put(context, item_key, item_value)
    msg = ["New value written into storage:", item_value]
    Notify(msg)

    return item_value
```

得到的字节码，在我的centos7上部署到polaris上，合约信息如下：
```
[root@centos ontio]# ontology contract deploy --code test.avm --name 'demo' --version '1.0' --author 'zou' --email 'tester@test.com' --desc 'demo' --account 1 --gaslimit 100000000 --needstore true
Password:
Deploy contract:
  Contract Address:ec9a9f99b894c333667b008b9df35faaf4536143
  TxHash:3ab9a35e2f5fd33ae0c63997b15489534c9cded3b10cba84d6347624c6050a17

Tip:
  Using './ontology info status 3ab9a35e2f5fd33ae0c63997b15489534c9cded3b10cba84d6347624c6050a17' to query transaction status
```
最终显示合约执行失败

- ####What did you expect to see?
返回某个整数 return some integer

- ####What did you see instead?
```
[root@centos ontio]# ontology contract invoke --address ec9a9f99b894c333667b008b9df35faaf4536143  --gaslimit 200000000 --prepare --return int
Invoke:436153f4aa5ff39d8b007b6633c394b8999f9aec Params:null
PrepareInvokeNeoVMSmartContact error:error code:47001 desc:SMARTCODE EXEC ERROR

Log:
2018/08/09 15:47:28.915857 [INFO ] GID 644377, PreExec: 
%!(EXTRA errors.ontError=[NeoVmService] service system call error!: [SystemCall] service not support: Neo.Storage.GetContext)
```

   **python版的合约调用会报错，C#是没问题的。smartx部署-运行也是会报错的，查询交易显示Failed**
请问该如何解决，非常感谢

**Comment by Arbio5zt** [comment]
@xris-hu could you pls help to check it, thanks.

**Comment by consensyx** [comment]
@Zou-XueYan you need change the import package  like this
from boa.interop.System.Runtime import Log, Notify
from boa.interop.System.Storage import Get, Put, GetContext

i modify your source code，it can be deployed and invoked in smartx

##################################

from boa.interop.System.Runtime import Log, Notify
from boa.interop.System.Storage import Get, Put, GetContext

def Main():
    
    if operation == 'GetItem':
        return GetItem()
    
    
def GetItem():
    context = GetContext()
    # This is the storage key we use in this example
    item_key = 'test-storage-key'

    # Try to get a value for this key from storage
    item_value = Get(context, item_key)
    msg = ["Value read from storage:", item_value]
    Notify(msg)

    if len(item_value) == 0:
        Notify("Storage key not yet set. Setting to 1")
        item_value = 1

    else:
        Notify("Storage key already set. Incrementing by 1")
        item_value += 1

    # Store the new value
    Put(context, item_key, item_value)
    msg = ["New value written into storage:", item_value]
    Notify(item_value)
    Notify(msg)
