### ISSUE TITLE
没有ONG无法转账转，怎么弄？

### ISSUE THREAD

**Issue by kenneth** [ontio/ontology#601]

**Comment by gasby88** [comment]
If you don‘t have ONG to transfer，you need to buy ONG from exchange.  ONG was listed at https://www.coinmex.com/spot/ong_usdt

**Comment by gasby88** [comment]
Meanwhile, if you hold ONT, it will release ONG, but you need to make a transfer transaction to unbound the ONG.

**Comment by kenneth** [comment]
@gasby88 
我持有ONT,会自动分发ONG给我？还是一定要去交易所买ONG.我是交易所提过来的，还没有转过账。

**Comment by gasby88** [comment]
Yes, but you won't get the ONG, after make a transaction.  持有ONT会获得ONG，但是此时的ONG时锁定的，你需要做一遍转账交易去解绑ONG，做完转账交易后，再做一个提取交易就可以获得自动分发的ONG了。所以，再你没有ONG的情况下，你也提取不了自动分发的ONG，这点跟NEO时不一样的。所以，第一笔ONG你需要别人转给你，或者你自己去交易所买。

**Comment by kenneth** [comment]
@gasby88 未绑定的ONG是什么意思，没有办法提取？

**Comment by Arbio5zt** [comment]
you can reference at [link](https://medium.com/ontologynetwork/everything-you-need-to-know-about-ong-582ed216b870).

**Comment by kenneth** [comment]
@luodanwg  明白了，就是我要找的，3Q

**Comment by voodoo12345** [comment]
Issue had been solved
