### ISSUE TITLE
ontology can not run in docker alpine image with "not found" error

### ISSUE THREAD

**Issue by lcgogo** [ontio/ontology#602]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
1.0.1

#### Does this issue reproduce with the latest release?
Not tried

#### What operating system are you using (such as macOS, Linux and Windows)?
docker alpine 3.8

#### What did you do?

I use alpine3.8 as docker base image, and copy the binary ontology to the image. Then run the image with followed error.

/bin # ./ontology
/bin/sh: ./ontology: not found
/bin # ./ontology --loglevel 0
/bin/sh: ./ontology: not found
/bin # ./ontology --loglevel=0
/bin/sh: ./ontology: not found
/bin # ./ontology --loglevel=0 --disablerpc --disableeventlog
/bin/sh: ./ontology: not found

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

#### What did you see instead?
some error without any enough information to trouble shooting.

#### Additional context
I use debian:stable-slim image as base image, and ontology runs normal. I attached both my dockerfile as below.

[ont-alpine38-Dockerfile.txt](https://github.com/ontio/ontology/files/2281999/ont-alpine38-Dockerfile.txt)
[ont-debian-slim-Dockerfile.txt](https://github.com/ontio/ontology/files/2282000/ont-debian-slim-Dockerfile.txt)

**Comment by qiluge** [comment]
It seems like OS caused the problem. I used your docker file build the alpine38 image and run it, the I find the ontology in /bin: 
![image](https://user-images.githubusercontent.com/19525062/44128898-093456f0-a078-11e8-9ed6-bba0626d151d.png)
Look at error info, `/bin/sh: ./ontology: not found`, alpine used `/bin/sh` to run ontology, so it is failed.
The I run the debian image, the ontology is run normally:
![image](https://user-images.githubusercontent.com/19525062/44128952-56ba2c9c-a078-11e8-90d6-8279500b1abc.png)
The debian run ontology straightly.
We will continue to find the suitable solution. If you have any new problem or specific solution, please reply here. Thank you!

**Comment by lightshine001** [comment]
Hi lcgogo，

You need the libc6-compat package for GNU libc compatibility. Please add the following line to Dockerfile.
     ` RUN apk add libc6-compat --no-cache`

After that,  ontology can work.
![image](https://user-images.githubusercontent.com/9333725/44130370-b99fb4a6-a07f-11e8-8d64-5428a0d95146.png)

Please be free to let me know if any progress.

**Comment by lcgogo** [comment]
@qiluge I think I solve this issue.
Add one line in dockerfile
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

see more at https://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker

**Comment by voodoo12345** [comment]
Docker alpine 3.8 issued had been solved
