### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by maiganne** [ontio/ontology#654]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?

v1.0.3-rc2
#### Does this issue reproduce with the latest release?

yes
#### What operating system are you using (such as macOS, Linux and Windows)?
windows

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.
when i execute the ont cli api like below
'''
ontology-windows-amd64.exe sendtx 00d1b718db75f401000000000000204e000000000000b33cd2b426dd12590f6f1f040c22220b62cb011a6e00c66b6a14b33cd2b426dd12590f6f1f040c22220b62cb011ac86a140cdbaf92575a66a63a8b042a859b4fc75344fa49c86a5ac86c51c1087472616e736665721400000000000000000000000000000000000000010068164f6e746f6c6f67792e4e61746976652e496e766f6b65000141405bb6f900265a3bd027c2fed1095810988cfe14a3b797597ef4697c1bde269c2f18e756b4d8a82488ebdaf66e016d060718382f7dad95761bbcc3843620fbda0923210338d128d0cb841e348e6374d7ac0316325c415eb227f04c48ec820070333391e8ac
'''
expected result does not come out but the error
'''
internal error, errunknown
'''

#### What did you expect to see?
'''
  TxHash:f8ea91da985af249e808913b6398150079cdfb02273146e4eb69c43947a42db2

Tip:
  Using './ontology info status f8ea91da985af249e808913b6398150079cdfb02273146e4eb69c43947a42db2' to query transaction status.
'''
#### What did you see instead?
'''
internal error, errunknown
'''

**Comment by Honglei-Cong** [comment]
hello, which network are you using? main net? test net?

**Comment by Honglei-Cong** [comment]
no response yet.
close temporarily.
