### ISSUE TITLE
can not invoke smart contract code, program runs failed!!!

### ISSUE THREAD

**Issue by shelmesky** [ontio/ontology#663]
I hava compile smart contract to AVM file by the compiler: [https://github.com/ontio/neo-go-compiler](https://github.com/ontio/neo-go-compiler)，then run the ontology program to invoke smart contract:

`./ontology contract invokeCode --code ./mycontract.avm`

The result is 

`hex to bytes error:encoding/hex: invalid byte: U+005E '^'`

**Comment by tanZiWen** [comment]
i think you need get source code from smartx, then you can put it on a txt document, you can deploy the source code first, then use appcall to invoke this contract. this have a example about how to call a smart contract: [appcall contract](https://github.com/ONT-Avocados/python-template/blob/master/Static_Call_Oep4/static_call_Oep4.py)

**Comment by tanZiWen** [comment]
i think you can use <code> ./ontology contract invokeCode </code> command to deploy and invoke a smart contract, i help it can help you!
