### ISSUE TITLE
JSON-RPC implementation doesn't match with protocol specification

### ISSUE THREAD

**Issue by silvesterdrago** [ontio/ontology#667]
protocol specification: https://www.jsonrpc.org/specification
convenient success response
{
    "error": null,
    "id": "id",
    "jsonrpc": "2.0",
    "result": "v1.0.4"
}
your response
{
    "desc": "SUCCESS",
    "error": 0,
    "id": "id",
    "jsonrpc": "2.0",
    "result": "v1.0.4"
}
convenient error response:
{
    "error": {"code": 42002, "message": "INVALID PARAMS"},
    "id": "id",
    "jsonrpc": "2.0",
    "result": ""
}
your error response:
{
    "desc": "INVALID PARAMS",
    "error": 42002,
    "id": "id",
    "jsonrpc": "2.0",
    "result": ""
}
This make problems with standard json-rpc clients, like python jsonrpclib

**Comment by Honglei-Cong** [comment]
OK.  Thanks.

**Comment by Honglei-Cong** [comment]
most SDK has been based on current response.
