### ISSUE TITLE
Wallet api calls

### ISSUE THREAD

**Issue by i3bitcoin** [ontio/ontology#684]
I'm wondering if there is any api calls (rpc or rest) available to work with wallet?
I see there are cli commands available, but what about api?

**Comment by xizho10** [comment]
try signature server https://github.com/ontio/ontology/blob/master/docs/specifications/sigsvr.md  ，release version  tool-*  in https://github.com/ontio/ontology/releases

**Comment by i3bitcoin** [comment]
Okay, will check. Thanks!

**Comment by i3bitcoin** [comment]
I've just checked and it works great! And is there a way to check the destination address(es) for each transaction in getblock or getrawtransaction calls, I only see Payer and Payload->Code.

Edit. Okay it seems I need to check each transaction with getsmartcodeevent.

Anyway thanks for your help @xizho10, you saved me a lot of time!
