### ISSUE TITLE
build unit test error in consensus package

### ISSUE THREAD

**Issue by guoleijie** [ontio/ontology#687]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
master stream

#### Does this issue reproduce with the latest release?
yes

#### What operating system are you using (such as macOS, Linux and Windows)?
macOS

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

#### What did you expect to see?
build success

#### What did you see instead?
![image](https://user-images.githubusercontent.com/14980280/48252356-83328980-e43f-11e8-9e40-6912f3c94034.png)
./node_utils_test.go:30:15: undefined: vconfig.StringID
./peer_pool_test.go:40:21: undefined: vconfig.NodeID
./peer_pool_test.go:52:15: undefined: vconfig.StringID
./peer_pool_test.go:81:15: undefined: vconfig.StringID
./peer_pool_test.go:98:15: undefined: vconfig.StringID
./peer_pool_test.go:122:15: undefined: vconfig.StringID
./peer_pool_test.go:138:15: undefined: vconfig.StringID

#### Additional context
I cannot find these two struct types, maybe someone missed them.
vconfig.NodeID and vconfig.StringID in github.com/ontio/ontology/consensus/vbft/config/config.go

**Comment by xiemylogos** [comment]
Thanks . I have fixed this problem in a future release. https://github.com/ontio/ontology/pull/688
