### ISSUE TITLE
convertNeoVmTypeHexString does not support Map type

### ISSUE THREAD

**Issue by backslash47** [ontio/ontology#690]
Hello, 
I am testing agains the TestNet and I am trying simple python smart contract containing:

```Notify(item)```

If the item is Map, the VM will return error:

```[NeoVmService] service system call error!: [SystemCall] service execute error!: [ConvertTypes] Invalid Types!```

I expected that the Notify will work also on Map type.

**Comment by tanZiWen** [comment]
yes, we don't support it now, because map is a complex struct, i think it is unnecessary to support. Do you have some good idea about it？

**Comment by tanZiWen** [comment]
if you want to use it, you can convert it to byte array, then client can deserialize it  to map.

**Comment by backslash47** [comment]
I implemented the whole VM in typescript. I based it on the Go implementation. I think the Map support is nearly complete in whole Go VM except the convertNeoVmTypeHexString method. It should be easy to add it there.
