### ISSUE TITLE
Authentication failed when transfering ONT in smart contract

### ISSUE THREAD

**Issue by bluesky139** [ontio/ontology#693]
#### What version of ontology are you using (`ontology --version`)?
v1.5.1

#### Does this issue reproduce with the latest release?
Yes.

#### What operating system are you using (such as macOS, Linux and Windows)?
Windows.

#### What did you do?
Open a local test ontology:
```
ontology --testmode --rest --loglevel 0
```

Created 2 accounts:
>  Index:1    Address:AKGMA1JNKSKD1MjpMCLJ38WQNTHVfjobbZ  Label: (default)
>  Index:2    Address:AGwzyQy7ujL5rNpYHTkXEYphHveK6uTmX8  Label:

Compile code on SmartX, download ABI and AVM.
```
        struct Transfer
        {
            public byte[] from;
            public byte[] to;
            public ulong amount;
        }
        
        public static readonly byte[] ontAddr = "AFmseVrdL9f9oyCzZefL9tG6UbvhUMqNMV".ToScriptHash();
        
        public static bool Main(string op, params object[] args)
        {
            return TransferONT((byte[]) args[0], (byte[]) args[1], (ulong) args[2]);
        }
        
        public static bool TransferONT(byte[] from, byte[] to, ulong ontAmount)
        {
            Transfer param = new Transfer { from = from, to = to, amount = ontAmount };
            object[] p = new object[1] { param };
            byte[] ret = ont.Native.Invoke(0, ontAddr, "transfer", p);
            if (ret[0] != 1)
            {
                return false;
            };
            return true;
        }
```

Deploy contract with command:
```
ontology contract deploy --name=t1 --code=t1.avm --author=AKGMA1JNKSKD1MjpMCLJ38WQNTHVfjobbZ --desc=example --email=hello@ontology.com --needstore --gaslimit=100000000
```

> Deploy contract:
>   Contract Address:17016ed5d21a6bfb326cf9eb0b19e3f7504f0a00
>   TxHash:55679bf1c0cc6100d2f7b40f4b3dc3c7fa33192549aba2eb8ec46378c609a640

Invoke contract method, try transfer ONT form account 1 to 2:
```
ontology contract invoke --address 17016ed5d21a6bfb326cf9eb0b19e3f7504f0a00 --params string:TransferONT,[bytearray:264afcc852f8d25d2e0bfb38f2d5fe31da6de70d,bytearray:0ce266a4a2f29ed7b23d59c45a0196c6b766a0cb,int:1] --prepare -return bool
```

Then got error log:
> Native serivce function execute error!: authentication failed.

#### What did you expect to see?
Successfully to transfer ONT in smart contract.

**Comment by Honglei-Cong** [comment]
[bytearray:264afcc852f8d25d2e0bfb38f2d5fe31da6de70d,
bytearray:0ce266a4a2f29ed7b23d59c45a0196c6b766a0cb,
int:1]

Should the first two item be address?
