### ISSUE TITLE
Is there a plan to support go module?

### ISSUE THREAD

**Issue by ryuyangu** [ontio/ontology#723]
Since go1.11,  golang  recommands go module instead of vendor. Will ontology & ontology-go-sdk do this support?

**Comment by ryuyangu** [comment]
Questions is: 
    I use  go1.11.2, and invoke ontology-go-sdk@1.0.6 in my project. Then `go build`  gets a go.mod like
```
	github.com/ontio/ontology v1.5.2
	github.com/ontio/ontology-crypto v1.0.4 // indirect
	github.com/ontio/ontology-eventbus v0.9.1 // indirect
	github.com/ontio/ontology-go-sdk v1.0.6

```
 `github.com/ontio/ontology v1.5.2` is the latest release tag for ontology but not match what `github.com/ontio/ontology-go-sdk v1.0.6`  invoked.  Error is `../../../go/pkg/mod/github.com/ontio/ontology-go-sdk@v1.0.6/native_contract.go:70:21: undefined: "github.com/ontio/ontology/core/utils".BuildNativeInvokeCode`.

There are some ways to fix it  but I think the best one is all ontology go-projects follow the go module constraint.

**Comment by Honglei-Cong** [comment]
no plan yet.
