### ISSUE TITLE
logging release/version info when ontology starting

### ISSUE THREAD

**Issue by Honglei-Cong** [ontio/ontology#729]
It's a good practice to log software release version on starting.

=========
current logging when starting ontology:
<---- logging ontology version here firstly?
2019/01/21 14:39:36.852540 ^[[0;36m[INFO ]^[[m GID 1, Config init success
  2 2019/01/21 14:40:10.886470 ^[[0;36m[INFO ]^[[m GID 1, Using account:AYLfTV7M8Cnu2rZvdo3gQsZdpxBGaAqjxL
  3 2019/01/21 14:40:10.886514 ^[[0;36m[INFO ]^[[m GID 1, Account init success

**Comment by qiluge** [comment]
https://github.com/ontio/ontology/pull/735
