### ISSUE TITLE
Block generation freezed @ block 2094299

### ISSUE THREAD

**Issue by travek** [ontio/ontology#742]
Hi!

As of now Explorer (explorer.ont.io) is showing that the network stuck at the block 2094299. No new blocks for more than 3 hours.

Please revert with the rootcase of the issue and the fix for the network please.

**Comment by Honglei-Cong** [comment]
resolved by https://github.com/ontio/ontology/pull/743

cc from public notice: 
On February 5th, 2019, the Ontology team started an urgent upgrade of the stake authorisation on the MainNet. Read more about this upgrade from here: https://link.medium.com/uvrJ1fErbU
