### ISSUE TITLE
Set leveldb openfile cache capacity

### ISSUE THREAD

**Issue by Honglei-Cong** [ontio/ontology#745]
#### Is your feature request related to a problem? Please describe.
As blockchain data grows, leveldb creates more files.  Default openfile cache capacity and block cache capacity may not enough.

#### Describe the solution you would like
Set the following options when opening leveldb:
* OpenFilesCacheCapacity
* WriteBuffer
* BlockCacheCapacity

**Comment by jonatanblockchain** [comment]
Just as reference, 

I remember this pull-request that finally wasn't commit https://github.com/ontio/ontology/pull/49/commits/1234532cd0403d38d1c5d4bb35e2a17a70fb74d9

**Comment by laizy** [comment]
@jonatanblockchain This commit tries to increment cache size to improve performance, which is the case for a simple leveldb test. but we have conducted an integration benchmark, which shows performance degradation and more memory consumption.

**Comment by Honglei-Cong** [comment]
testcases for performance comparison:
1. execution all transactions in main-net by importing blocks
2. processing block/tx syncing requests from 100 remote nodes
3. 1,000,000 transactions performance stress test

**Comment by Honglei-Cong** [comment]
resolved by https://github.com/ontio/ontology/commit/42888aaf9671c587722cf6e1b0896cda9f563152
