### ISSUE TITLE
In the latest release, there is no createaccount method.

### ISSUE THREAD

**Issue by uranus97s** [ontio/ontology#746]
#### How to create an account using rpc call
pls !

**Comment by Honglei-Cong** [comment]
AccountCreation is Private-Key/Public-Key/Address generation.
It should be created locally.

SDK provides NewAccount interface.

**Comment by uranus97s** [comment]
@Honglei-Cong  I am very grateful to you.
I used the tool of the ontology but when using createaccount method, my account was received at mainnet network. I'm working with testmode network, so the address is not valid. Is there any way for me createaccount method and the result returned is the account at testmode network.
Help me pls!

**Comment by Honglei-Cong** [comment]
Account address in mainnet network cal also be used in testmode network.  
Your address can be valid on any network as long as it had received transferred token.

If you started testmode network with './ontology --testmode', all tokens are in your default ontology account (usually as ./wallet.dat).   You can create new account with SDK.NewAccount interface, and transfer some ONT from your default wallet to new account.
