### ISSUE TITLE
question about calculation of txRoot in constructBlock@msg_builder.go

### ISSUE THREAD

**Issue by Honglei-Cong** [ontio/ontology#747]
one question from community.

一、详细说明：
这有可能是我理解错了你们的共识算法，如果是的话请忽略。。。看到你们最新的这个commit

https://github.com/ontio/ontology/commit/9324805e33761d1d30dfb54276be21c4a2332f28

在msg_builder.go中的

constructBlock函数中有

blockRoot := ledger.DefLedger.GetBlockRootWithNewTxRoots(lastBlock.Block.Header.Height, []common.Uint256{lastBlock.Block.Header.TransactionsRoot, txRoot})

第一个参数是上一个区块的高度，第二个参数是上一个和这一个区块的merkle tree的根，传入

GetBlockRootWithNewTxRoots 后会到

//GetBlockRootWithNewTxRoots return the block root(merkle root of blocks) after add a new tx root of block

func (this *LedgerStoreImp) GetBlockRootWithNewTxRoots(startHeight uint32, txRoots []common.Uint256) common.Uint256 {

this.lock.RLock()

defer this.lock.RUnlock()

// the block height in consensus is far behind ledger, this case should be rare

if this.currBlockHeight &gt; startHeight+uint32(len(txRoots))-1 {

// or return error?

return common.UINT256_EMPTY

}

needs := txRoots[this.currBlockHeight+1-startHeight:]

return this.stateStore.GetBlockRootWithNewTxRoots(needs)

}

this.currBlockHeight+1-startHeight 这里的话我没理解错的话startHeight是上一个区块的高度(solo模式下这是新一个区块的高度)，那这里this.currBlockHeight+1-startHeight 就变成2了

也就是说，穿进去的只有两个txRoot,这里又是2的话，那数组就是nil了。

同时，还有一个问题，这个commit中

func (this *LedgerStoreImp) submitBlock(block *types.Block, result store.ExecuteResult) error {

blockHash := block.Hash()

blockHeight := block.Header.Height

blockRoot := this.GetBlockRootWithNewTxRoots(block.Header.Height, []common.Uint256{block.Header.TransactionsRoot}) &lt;--- 这里的第二个参数为什么只传了一个TransactionRoot进去？

if block.Header.Height != 0 &amp;&amp; blockRoot != block.Header.BlockRoot {

return fmt.Errorf(&quot;wrong block root at height:%d, expected:%s, got:%s&quot;,

block.Header.Height, blockRoot.ToHexString(), block.Header.BlockRoot.ToHexString())

}

这个blockRoot的计算方法和前面那个msg_builder的不同啊，也就是说他这里只有自己这个block的txRoot，而msg_builder却有上一个block的txRoot，这就比较奇怪了。

不知道是不是我的理解有问题，如果是的话非常抱歉。。。

二、漏洞证明：

三、修复方案：

**Comment by laizy** [comment]
1. 区块的落账分为ExecuteBlock和SubmitBlock两个步骤，因此共识出的区块落账通常会有一个区块的延迟：比如当前共识正准备打包H+1的区块，但是账本层还没有完整落完H区块，currBlockHeight为H-1，如果只把H+1区块的merkle root作为参数，则因为账本层还没有H区块的merkle root，导致计算出错。所以至少需要提供currBlockHeight+1至H+1高度之间的所有区块merkle根。
2. 账本存储区块时可以从两个入口获取区块：一个是共识模块，一个是从其他节点通过网络同步，两者是并发执行的。所以如果某一个节点的共识模块滞后了或者同步速度较快。共识节点在尝试出H+1区块时，账本层可能已经通过同步的方式落账了区块H，甚至H+1，H+2等区块。因此调用的参数增加了一个startHeight参数，用于指定参数中第一个merkle root所在的高度。

回到问题：
1. 如果currBlockHeight为10， startHeight为11，要构造高度为12的区块，this.currBlockHeight+1-startHeight 为 0，也就是两个merkle root均参与计算
2. 同步速度较快currBlockHeight为11，startHeight为11，要构造高度为12的区块，this.currBlockHeight+1-startHeight 为 1，也就是只需要高度12的merkle root参与计算。
3. 共识滞后，currBlockHeight为12，startHeight为11，共识试图构造高度为12的区块(由于其他节点已经出了区块12，因此这个节点最终出不了这个区块)，this.currBlockHeight+1-startHeight 为 2，不需要参数中的任何merkle root，因为账本已经落账了区块12，因此直接从账本里返回。
4. 共识严重滞后，currBlockHeight为13+，startHeight为11，共识试图构造高度为12的区块，这时this.currBlockHeight > startHeight+uint32(len(txRoots))-1 为真，直接返回空hash。

**Comment by qiushui777** [comment]
Thanks。是我先前对共识滞后情况理解有误。
