### ISSUE TITLE
my node have no notify data of some transactions

### ISSUE THREAD

**Issue by bitcodernull** [ontio/ontology#749]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?

1.5.3

#### Does this issue reproduce with the latest release?
yes

#### What operating system are you using (such as macOS, Linux and Windows)?

linux 

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

my node has the transactions, but not have the notify of the transaction 
not all the transactions

**Comment by tanZiWen** [comment]
./ontology info status txhash, you can use this command to show notify info.
