### ISSUE TITLE
GO annotation for citrus species

### ISSUE THREAD

**Issue by trang-phan** [ontio/ontology#756]
I would like to request GO annotation for citrus sinensis. 
I'm using CLC Genomics Workbench for my RNAseq analysis. Although they offer options for doing GO enrichment, the GO annotation file needs to be downloaded from a separate source (geneontology.org website) which unfortunately does not have information for citrus species. 
It will be very helpful if you could help generate one that is compatible with CLC software.
Thank you very much!

**Comment by laizy** [comment]
this is a blockchain project, which has nothing to do with http://geneontology.org/ you mentioned. :)
