### ISSUE TITLE
Distributed data exchange protocol

### ISSUE THREAD

**Issue by caowencai** [ontio/ontology#770]
In the white paper, there is something about distributed data exchange protocol.
If I want to exchange data  via ONT, where to set up or implement **ddep** by self?
I find it hard to get useful ingormation in the dev-docs, any tips?

Thanks a lot.

**Comment by Honglei-Cong** [comment]
@xiaomin49

**Comment by Honglei-Cong** [comment]
Ontology WhitePaper 2.0 is going to be released this month.
DDXF framework will be included.
