### ISSUE TITLE
WASM-VM Performance Improving

### ISSUE THREAD

**Issue by Honglei-Cong** [ontio/ontology#778]
related issues:
- [x] add compiled wasm module: https://github.com/ontio/wagon/pull/8
- [x] cache compiled module: https://github.com/ontio/ontology/pull/812
- [x] reduce inital memory allocation: https://github.com/ontio/ontology-wasm-cdt-rust/pull/38
- [x] ~~avoid data copy and memory allocation: https://github.com/ontio/ontology-wasm-cdt-rust/issues/40~~

**Comment by ghost** [comment]
@laizy , can you please leave a tiny comment when closing issues, so one know why it was closed? it is not always clear.

**Comment by laizy** [comment]
@lazaridiscom all releted issues are addressed.
