### ISSUE TITLE
readonly wallet ?

### ISSUE THREAD

**Issue by chengmiaook** [ontio/ontology#805]
#### Additional context
hello,it suporrt the readonly wallet ? can i do  save pubkey in wallet but the prikey in database  please ?c

**Comment by Honglei-Cong** [comment]
Currently, wallet-data is saved in wallet file, it usually is named 'wallet.dat'.

Yes, you can save pubkey in wallet, but private key in database.  It's not supported now.
Loading private key/account from remote server seems an enterprise requirement.
I think Ontology may not take it as high priority task.
