### ISSUE TITLE
is wasm contract support？

### ISSUE THREAD

**Issue by hunjixin** [ontio/ontology#814]

**Comment by laizy** [comment]
Currently under intense development, but the chain runtime api is nearly stable, so you can try to write some contract use [rust](https://github.com/ontio/ontology-wasm-cdt-rust) or [cpp](https://github.com/ontio/ontology-wasm-cdt-cpp) now.

**Comment by hunjixin** [comment]
@laizy cpp to wsam is quietly big,how can reduces the size

**Comment by laizy** [comment]
you can use wasm-opt: https://github.com/WebAssembly/binaryen

**Comment by hunjixin** [comment]
not work,but it seems because asm.js file  that generates from c++ is too big
```

```

**Comment by laizy** [comment]
why you not generate wasm file directly instead of asm.js file?

**Comment by hunjixin** [comment]
i am using emcc, this tool will generate wasm from asm.js.
how to generate wasm file directly,? or some tool will help

**Comment by laizy** [comment]
I mostly maintain the [rust](https://github.com/ontio/ontology-wasm-cdt-rust) version. maybe @carltraveler can answer your question.

**Comment by hunjixin** [comment]
@carltraveler  wasm from c++ has import “env" . this leads to an error

**Comment by carltraveler** [comment]
emcc is for web.  I have build a development tool of wasm cpp on ontology. please refer to [README.md](https://github.com/ontio/ontology-wasm-cdt-cpp/blob/master/README.md). just use ont_cpp yourcode.cpp.

**Comment by carltraveler** [comment]
@hunjixin  ont_cpp compiler also have function import from "env".  all this fucntion is ontology blockchain api. function list refer to [service.h](https://github.com/ontio/ontology-wasm-cdt-cpp/blob/master/install/include/ontiolib/service.h)

**Comment by Honglei-Cong** [comment]
for compiler, please reference to repo https://github.com/ontio/ontology-wasm-cdt-rust and https://github.com/ontio/ontology-wasm-cdt-cpp
for wasm-vm, please reference to branch wasm
