### ISSUE TITLE
Found an error in ontrpcapi.md

### ISSUE THREAD

**Issue by lpffzx** [ontio/ontology#83]
Found an error in docs/specifications/ontrpcapi.md, the api name and instructions don't match, as follows:

#### 6. getgenerateblocktime

Get a list of unconfirmed transactions in memory.

#### Example

Request:

```
{
  "jsonrpc": "2.0",
  "method": "getgenerateblocktime",
  "params": [],
  "id": 1
}
```

Reponse:

```
{
  "desc":"SUCCESS",
  "error":0,
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    "b4534f6d4c17cda008a76a1968b7fa6256cd90ca448739eae8e828698ccc44e7"
  ]
}
```

These are the undetermined transactions received by the node, that is, those with zero confirmed transactions.

**Comment by lucas7788** [comment]
已解决

**Comment by lucas7788** [comment]
@lpffzx ffe6560c32e08dd9729ff41f8982183947e047f0   已解决
