### ISSUE TITLE
How to get private key from wallet.dat

### ISSUE THREAD

**Issue by roccomuso** [ontio/ontology#844]
I got my wallet password, how can I get the plain privateKey from my `wallet.dat`, with the ontology-cli tool?
I saw `scrypt` is involved.

**Comment by Honglei-Cong** [comment]
Hi, ontology-cli cant print plain privateKey on screen.
You can use other wallet, for example OWallet https://github.com/ontio/OWallet/releases, to export your private key in WIF from wallet.dat.

**Comment by roccomuso** [comment]
What I'm looking for is key generation with ed25519, don't know if OWallet uses this algorithm.

**Comment by laizy** [comment]
you can generate your `wallet.dat` use `ontology`, and import it use OWallet.

**Comment by yoge23** [comment]
@roccomuso do you still kept the file, what type of wallet you use?

**Comment by yoge23** [comment]
@roccomuso do you still kept the wallet.dat?
