### ISSUE TITLE
can not claim ONG from Owallet

### ISSUE THREAD

**Issue by Kelsoken** [ontio/ontology#847]
can anyone help me?
I have an ONT wallet but cannot claim my ONG :-(
can someone please send ONG to my wallet, I will greatly appreciate this,
my wallet address is:
ASCmxgVzxfe2WosoCCh6hCHZ59TNau5N9V

**Comment by Honglei-Cong** [comment]
ONG balance of ASCmxgVzxfe2WosoCCh6hCHZ59TNau5N9V had been 0.27805964.
I take this as resolved.
