### ISSUE TITLE
1.6版本对日志是不是做了修改

### ISSUE THREAD

**Issue by zhangsj** [ontio/ontology#851]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
1.6

#### Does this issue reproduce with the latest release?
1.6

#### What operating system are you using (such as macOS, Linux and Windows)?
linux

在1.5.3版本中使用supervisor启动程序没问题，在1.6中无法正常启动，无日志输出。
supervisor配置
[program:ont]
user=root
command=ontology --rest
numprocs=1 ; number of processes copies to start (def 1)
directory=/opt/ont ; directory to cwd to before exec (def no cwd)
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/ontology_out.log
stderr_logfile=/var/log/ontology_err.log
stdout_logfile_maxbytes = 20MB ; stdout 日志文件大小，默认 50MB
stdout_logfile_backups = 20 ; stdout 日志文件备份数

**Comment by laizy** [comment]
经排查，是依赖上游的一个包导致的，下一个版本将修复。

**Comment by Honglei-Cong** [comment]
#850
