### ISSUE TITLE
mainnet sychronization error

### ISSUE THREAD

**Issue by dwjpeng** [ontio/ontology#857]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?

v1.6.0-0-g1e24e0f
#### What operating system are you using (such as macOS, Linux and Windows)?
Linux

#### What did you do?
![image](https://user-images.githubusercontent.com/8435346/56550473-4bb43580-65b8-11e9-844e-2e2d9c4248e3.png)
reaching height 2999999, ontology can not fetch the next one . There is an error "[p2p]error read from 45.33.105.19:54872 :read tcp local addrress:20338->45.33.105.19:54872: read: connection reset by peer";

**Comment by Honglei-Cong** [comment]
Hi, ledger consistency checking is enforced at version 1.6.0.  If you met this issue, it means your local blockchain ledger is inconsistent with major nodes in the network.   
It's suggested to resync from the first block with v1.6.1.

**Comment by ak47j** [comment]
Hello, the same on my side,
Was it worked when resync from the first block with v1.6.1 @dwjpeng ?
Resyncing from the first block took my pain in some days... don't know what happen will be there!
