### ISSUE TITLE
error:saveBlock error state merkle root mismatch!

### ISSUE THREAD

**Issue by smithy9901** [ontio/ontology#861]
Not gaining height, stopped at block 2999999

2019/04/24 16:54:35.285839 [ERROR] GID 6016, Ledger AddBlock BlockHeight:3000000 BlockHash:3e09c813a1e1175aab4a362df8509e4e5adcb999941e516667b13de0ced0bbf6 error:saveBlock error state merkle root mismatch!
2019/04/24 16:54:35.285865 [WARN ] GID 6016, [p2p]saveBlock Height:3000000 AddBlock error:saveBlock error state merkle root mismatch!

ver 1.6.1
Linux 16.04

**Comment by Honglei-Cong** [comment]
Hi, 
If your Ontology node stopped syncing at block 2999999, it probably means your local blockchain ledger has been inconsistent with other nodes.
The reason may be that some unstable versions of Ontology had been used before.
I suggest to re-synchronise from the first block with v1.6.1.

**Comment by olizax** [comment]
same error
1.6.0
ubuntu 18.04

**Comment by quocnhan** [comment]
even when i updated the version to 1.6.2, this bug are still here

**Comment by Honglei-Cong** [comment]
which height? @olizax @quocnhan

**Comment by quocnhan** [comment]
@Honglei-Cong 2428485 in 1.6.2, testnet
