### ISSUE TITLE
NewLedger error

### ISSUE THREAD

**Issue by ddzyan** [ontio/ontology#880]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
v1.6.2-alpha

#### What operating system are you using (such as macOS, Linux and Windows)?
Linux

#### What did you do?
`
./ontology-linux-amd64
`
`
2019/05/08 00:16:52.896505 [INFO ] GID 1, Config init success
2019/05/08 00:16:52.944036 [ERROR] GID 1, NewLedger error:NewLedgerStore error NewStateStore error init error merkle tree size is inconsistent with blockheight: 3552225
`

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

#### What did you expect to see?
Recovery block synchronization

**Comment by Honglei-Cong** [comment]
This may caused by partial writing of ontology ledger when process is shutdown.
Some data in ledger has not been in consistent state.
You'll have to resync from the first block currently.  We're implementing ledger recovery function to try recovering inconsistent ledger.
