### ISSUE TITLE
Wallet stucked at 2999999

### ISSUE THREAD

**Issue by ak47j** [ontio/ontology#886]
Hi there,

I am using wallet version 1.6.0 in Ubuntu 16.04

and wallet syncing stuck at 2999999

error terminal got:

Ledger AddBlock BlockHeight:3000000 BlockHash:3e09c813a1e1175aab4a362df8509e4e5adcb999941e516667b13de0ced0bbf6 error:saveBlock error state merkle root mismatch!

Could you please address the problem?
Thanks

**Comment by laizy** [comment]
please update to version 1.6.1

**Comment by love386** [comment]
How can I upgrade to version 1.6.1?

**Comment by love386** [comment]
Thank you

**Comment by love386** [comment]
I have the same mistake with him.

**Comment by laizy** [comment]
@love386 download the binary at the [release page ](https://github.com/ontio/ontology/releases/tag/v1.6.1), and replace the original binary, restart `ontology`.
