### ISSUE TITLE
P2P : handshake with consensus node in dualport seems not work well

### ISSUE THREAD

**Issue by tpkeeper** [ontio/ontology#890]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
master latest

#### What operating system are you using (such as macOS, Linux and Windows)?

window testnet 

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

## after handshaking with sync port  ,it can't handshake with the consensus port ,as the remotepeer's consport always return 0
```
//consensus port connect
			if config.DefConfig.P2PNode.DualPortSupport && remotePeer.GetConsPort() > 0 {
				addrIp, err := msgCommon.ParseIPAddr(addr)
				if err != nil {
					log.Warn(err)
					return
				}
				nodeConsensusAddr := addrIp + ":" +
					strconv.Itoa(int(remotePeer.GetConsPort()))
				go p2p.Connect(nodeConsensusAddr, true)
			}
```

**Comment by laizy** [comment]
`dualport` is not supported, we may need remove the legacy code .
