### ISSUE TITLE
 state merkle root mismatch

### ISSUE THREAD

**Issue by love386** [ontio/ontology#905]
How can I upgrade to version 1.6.1?

**Comment by love386** [comment]
Ledger AddBlock BlockHeight:3000000 BlockHash:3e09c813a1e1175aab4a362df8509e4e5adcb999941e516667b13de0ced0bbf6 error:saveBlock error state merkle root mismatch!

**Comment by love386** [comment]
ontology version v1.6.0-3-g82442f1
ubuntu  16.04

**Comment by laizy** [comment]
yes, you need upgrade to version 1.6.1.

**Comment by love386** [comment]
I don't know how to upgrade, is there any documentation, thank you

**Comment by laizy** [comment]
@love386 download the binary at the [release page ](https://github.com/ontio/ontology/releases/tag/v1.6.1), and replace the original binary, restart `ontology`.

_Originally posted by @laizy in https://github.com/ontio/ontology/issues/886#issuecomment-492988902_

**Comment by love386** [comment]
Thank you, will my existing user accounts and assets be affected?

**Comment by laizy** [comment]
no

**Comment by love386** [comment]
Thank you

**Comment by love386** [comment]
Hello, I downloaded the ontology-linux-amd64 binary file, and added the execution permission, replaced the original command, restart the body, what is the problem?

![image](https://user-images.githubusercontent.com/45838695/57912267-76926080-78bc-11e9-9d1d-8bf05f6bbc7b.png)

**Comment by laizy** [comment]
you need delete your Chain, and re-sync from genesis block.

**Comment by love386** [comment]
That is to delete the data I have synchronized before, and then re-synchronize the data on the chain?

**Comment by love386** [comment]
If I clear the previously synchronized data, will my existing user accounts and assets be affected? Thank you.

**Comment by love386** [comment]
The ontology wallet can export the user's keys file, which is the user's asset information.

**Comment by laizy** [comment]
you only need save your wallet, the asset information is saved on the blockchain. you can get user's asset information in [blockchain explorer](https://explorer.ont.io/)

**Comment by love386** [comment]
Ok, thank you very much.

**Comment by love386** [comment]
Hello Upgrade to 1.6.1 sync to 376526 error message as shown below

**Comment by love386** [comment]
![image](https://user-images.githubusercontent.com/45838695/57927962-16161a00-78e2-11e9-9656-967b614c7879.png)

**Comment by love386** [comment]
What is the problem, thank you

**Comment by love386** [comment]
Restarted the next body and continued to synchronize, what will be the problem?

**Comment by love386** [comment]
But there is still an error in the picture below.
![image](https://user-images.githubusercontent.com/45838695/57928978-ac4b3f80-78e4-11e9-8f24-fa2ec6af6bce.png)

**Comment by laizy** [comment]
Some remote nodes may reject to sync data to you. It is **OK** if `CurrentBlockHeight` increases

**Comment by love386** [comment]
Nǐ hǎo   yǒu gè cuòwù, rúxià tú, qǐngwèn shì shénme yuányīn
21/5000
Hello, there is an error, as shown below, what is the reason?

![image](https://user-images.githubusercontent.com/45838695/57962749-9c1b7a80-794d-11e9-8312-3ff5e7482bfc.png)

**Comment by love386** [comment]
Hello, how can I kill my ont main wallet after upgrading to 1.6.1?
![image](https://user-images.githubusercontent.com/45838695/57966501-3c40c600-7985-11e9-8d96-4158de436abe.png)

**Comment by love386** [comment]
Hello, after I upgraded the main body wallet to 1.6.1, why would I kill it?
![image](https://user-images.githubusercontent.com/45838695/57966549-06e8a800-7986-11e9-96f9-650db5266c30.png)

**Comment by love386** [comment]
Hello, after the ont main wallet is upgraded to 1.6.1, why is it automatically killed?
![image](https://user-images.githubusercontent.com/45838695/57966575-80809600-7986-11e9-9e10-1da6cae62b7d.png)

**Comment by laizy** [comment]
maybe it is out of memory.

**Comment by love386** [comment]
ok  Thank you
