### ISSUE TITLE
getsmartcodeevent keep returns null

### ISSUE THREAD

**Issue by heshuchao** [ontio/ontology#908]
ontology version is "v1.6.1-0-gc46ec1f"

tried to call the method with both block height and transaction hash ,
no error returns ,but the respond is "nul"l

**Comment by Honglei-Cong** [comment]
Please check your code :)
From our test, both interfaces works well.

## query with tx hash

curl http://dappnode1.ont.io:20334/api/v1/smartcode/event/txhash/a6e3e46cf9ec57dfb00502d9d47236f083d590bf8e0b41d69540dcd907eba8df
{"Action":"getsmartcodeeventbyhash","Desc":"SUCCESS","Error":0,"Result":{"TxHash":"a6e3e46cf9ec57dfb00502d9d47236f083d590bf8e0b41d69540dcd907eba8df","State":1,"GasConsumed":10000000,"Notify":[{"ContractAddress":"0200000000000000000000000000000000000000","States":["transfer","AUzaAKup8HgvikrVVfbLCEDweY7fdepUUE","AXgmQkSxKuUtGDLFkiQsVRstZaLYtUx9wj",10000000]},{"ContractAddress":"0b4c91c1ebaa5a0beb97bd5a3367be89efb98aae","States":["3131315f7061796f72646572","ae8ab9ef89be67335abd97eb0b5aaaebc1914c0b","910072442a04291510d7c92db716a43b9985cd44","313535383233343838323937343132333333","80969800"]},{"ContractAddress":"0b4c91c1ebaa5a0beb97bd5a3367be89efb98aae","States":"7472616e73666572204f6e672073756363656564"},{"ContractAddress":"0200000000000000000000000000000000000000","States":["transfer","AUzaAKup8HgvikrVVfbLCEDweY7fdepUUE","AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",10000000]}]},"Version":"1.0.0"}


## query with block height

curl http://dappnode1.ont.io:20334/api/v1/smartcode/event/transactions/3967379

{"Action":"getsmartcodeeventbyheight","Desc":"SUCCESS","Error":0,"Result":[{"TxHash":"eff1c1b090bf70e55eee4a9d8c2ff01eb1c2e5593c928655434aa6cde423f2a2","State":1,"GasConsumed":10000000,"Notify":[{"ContractAddress":"0200000000000000000000000000000000000000","States":["transfer","ANinxJ2JxH91EWvkynyEVqMbWUD3EZaCrG","AUxXb3rwzApdR35fY2pdJUnD9L3ZFuCDFg",10000000]},{"ContractAddress":"d32eb834740c78c864ddd615a7c24b994a779d90","States":["3131315f7061796f72646572","909d774a994bc2a715d6dd64c8780c7434b82ed3","4c33b706297fdc601be168bbc718405a03f176f6","313535383233343838323733333132333333","80969800"]},{"ContractAddress":"d32eb834740c78c864ddd615a7c24b994a779d90","States":"7472616e73666572204f6e672073756363656564"},{"ContractAddress":"0200000000000000000000000000000000000000","States":["transfer","ANinxJ2JxH91EWvkynyEVqMbWUD3EZaCrG","AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",10000000]}]},{"TxHash":"a6e3e46cf9ec57dfb00502d9d47236f083d590bf8e0b41d69540dcd907eba8df","State":1,"GasConsumed":10000000,"Notify":[{"ContractAddress":"0200000000000000000000000000000000000000","States":["transfer","AUzaAKup8HgvikrVVfbLCEDweY7fdepUUE","AXgmQkSxKuUtGDLFkiQsVRstZaLYtUx9wj",10000000]},{"ContractAddress":"0b4c91c1ebaa5a0beb97bd5a3367be89efb98aae","States":["3131315f7061796f72646572","ae8ab9ef89be67335abd97eb0b5aaaebc1914c0b","910072442a04291510d7c92db716a43b9985cd44","313535383233343838323937343132333333","80969800"]},{"ContractAddress":"0b4c91c1ebaa5a0beb97bd5a3367be89efb98aae","States":"7472616e73666572204f6e672073756363656564"},{"ContractAddress":"0200000000000000000000000000000000000000","States":["transfer","AUzaAKup8HgvikrVVfbLCEDweY7fdepUUE","AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",10000000]}]}],"Version":"1.0.0"}

**Comment by heshuchao** [comment]
I know why now,
I start the node with  --disable-tx-pool-pre-exec and  --disable-sync-verify-tx, after delete these two configurations ,the getsmartcodeevent method works correct.
