### ISSUE TITLE
deserializing public key failed: unrecognized algorithm label

### ISSUE THREAD

**Issue by pigxo** [ontio/ontology#917]
Please answer these questions before submitting your issue. Thanks!

#### What version of ontology are you using (`ontology --version`)?
 ../ontology  --version
ontology version v1.6.2-alpha-0-g66273d5

#### Does this issue reproduce with the latest release?

Yes
#### What operating system are you using (such as macOS, Linux and Windows)?
linux docker

#### What did you do?

If possible, provide a recipe for reproducing the error. A complete runnable program is good. Attach the project archive with issue.

搭建用户定义的网络，7个共识节点，1个同步节点，共识节点能够共识并且持续出块，但是当同步节点与共识节点的块相差大约10块的时候，去同步块，变不能同步到，然后报错

deserializing public key failed: unrecognized algorithm label

2019/05/24 02:23:25.977133 [INFO ] GID 30, CurrentBlockHeight = 0
2019/05/24 02:23:27.966699 [INFO ] GID 4109, [p2p]error read from 172.18.0.16:40428 :deserialze BlkHeader error: deserializing public key failed: unrecognized algorithm label

#### Additional context
这个问题如果是同步节点与共识节点的块相差不大，也是可以正常同步的。

V1.6.1 版本不存在这个问题。

**Comment by laizy** [comment]
thanks for report. we will investigate this.
