### ISSUE TITLE
Missing MAX_ARRAY_SIZE check

### ISSUE THREAD

**Issue by WyattMufson** [ontio/ontology#930]
As discussed by me and @laizy in https://github.com/ontio/OEPs/pull/51 - `validateAppend` isn't checking the `MAX_ARRAY_SIZE` (https://github.com/ontio/ontology/blob/master/vm/neovm/func_validate.go#L571)

**Comment by laizy** [comment]
@tanZiWen

**Comment by tanZiWen** [comment]
great, we will fix this question.

**Comment by Honglei-Cong** [comment]
#958
