### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by WyattMufson** [ontio/ontology#936]
#### What version of ontology are you using (`ontology --version`)?
Building from source

#### Does this issue reproduce with the latest release?
Yes

#### What operating system are you using (such as macOS, Linux and Windows)?
macOS 10.14.4

#### What did you do?

`git clone`
`git pull`
`make all`
`make docker`
`docker run ontio/ontology`

Get the following error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./ontology\": permission denied": unknown.
ERRO[0001] error waiting for container: context canceled
```

#### What did you expect to see?
Expect docker to start correctly

#### What did you see instead?
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./ontology\": permission denied": unknown.
ERRO[0001] error waiting for container: context canceled
```

#### Additional context

Using Docker Community Edition version 18.06.1-ce-mac73 (26764)

**Comment by WyattMufson** [comment]
Updating to Docker Desktop Community version 2.0.0.3 (31259) did not fix the issue

**Comment by Honglei-Cong** [comment]
Thanks. We'll look at the issue.

**Comment by Honglei-Cong** [comment]
I made some quick test with Linux, not get the issue.

```
make docker
docker run -p 20334:20334 -d ontio/ontology --rest --ws

curl http://localhost:20334/api/v1/block/height
{"Action":"getblockheight","Desc":"SUCCESS","Error":0,"Result":1539,"Version":"1.0.0"}
```

**Comment by WyattMufson** [comment]
@Honglei-Cong does it not work on macOS?

Running what you put prints:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"./ontology\": permission denied": unknown.
```

**Comment by WyattMufson** [comment]
I think this is an issue with my GOPATH and not with Ontology. Will update this when I figure it out.

**Comment by WyattMufson** [comment]
@Honglei-Cong the issue is that it doesn't work outside of the GOPATH. So if I do it all in the right directory, running the following starts Docker:

```
docker run ontio/ontology
```

However, when I try running it with `--testmode` I get:

```
2019/06/02 10:45:53.432049 [INFO ] GID 1, ontology version v1.7.0-alpha-3-gc242dda0
2019/06/02 10:45:53.432104 [INFO ] GID 1, Config init success
2019/06/02 10:45:53.432150 [ERROR] GID 1, initWallet error:Cannot find wallet file:./wallet.dat. Please create wallet first
```

I have already created a wallet, `wallet.dat` such that the structure is:

```
$ tree
└── ontology
    ├── ontology
    └── wallet.dat
```

**Comment by WyattMufson** [comment]
And running `./ontology --testmode` works and finds the wallet.

**Comment by WyattMufson** [comment]
Specifying the full path with the `--wallet` flag does not resolve the issue.

**Comment by WyattMufson** [comment]
@laizy do you have any idea about this?

**Comment by Honglei-Cong** [comment]
please bind local wallet file to docker.

```
docker run -it -p 20334:20334 -v `pwd`/wallet.dat:/var/ontology/wallet.dat  ontio/ontology --testmode --rest
```

**Comment by WyattMufson** [comment]
So that successfully starts Docker, but now the python sdk doesn't see the private net when I do:
```
sdk.rpc.connect_to_localhost()
result = sdk.rpc.send_raw_transaction_pre_exec(tx)
```

**Comment by Honglei-Cong** [comment]
rpc port is 20336.
Please make sure starting docker with param `-p 20336:20336`, to mapping port 20336 from docker container to localhost.

**Comment by WyattMufson** [comment]
@Honglei-Cong you did it! This also resolves https://github.com/ontio/ontology-python-sdk/issues/346
