### ISSUE TITLE
PackedList append issue

### ISSUE THREAD

**Issue by WyattMufson** [ontio/ontology#946]
I am testing the PackedList for OEP5 (https://github.com/TowerBuilders/PackedList/blob/master/packed.py)

I am deploying the contract to a private net running 1.7.0-alpha. I am deploying and invoking the contract with the python sdk.

And when adding around 10 items I get the error:

> [NeoVmService] service system call error!: [SystemCall] service execution error!: runtime serialize: can not serialize circular reference data

I think the issue is in `PackedAppend` (https://github.com/TowerBuilders/PackedList/blob/master/packed.py#L111)

I see the error is called here: https://github.com/ontio/ontology/blob/fa9c2fe27daf1bc2fb67a28b0188b051cdef5a5e/smartcontract/service/neovm/runtime.go#L165

@laizy @Honglei-Cong

**Comment by WyattMufson** [comment]
To clarify, it gets the error after 10 appends when `MAXIMUM_ARRAY_LENGTH` is 2

When `MAXIMUM_ARRAY_LENGTH` is 5 it errors around 20.
When `MAXIMUM_ARRAY_LENGTH` is 1024 it errors in thousands.

**Comment by WyattMufson** [comment]
At 1024 it errors at 9231

**Comment by WyattMufson** [comment]
@laizy So it appears that a PackedList can only have a depth of 9, so the maximum amount of items is equal to:

`MAXIMUM_ARRAY_LENGTH` * 9 - 8

**Comment by WyattMufson** [comment]
So it should either be capped at that value or dynamically allocate additional arrays. That would at least enable a maximum of what, `1024 * MAXIMUM_ARRAY_LENGTH * 9 - 8`?

**Comment by WyattMufson** [comment]
I've concluded that the depth control is at 7. So I have created a new type, DynamicList that can hold:
```
MAXIMUM_ARRAY_LENGTH * (MAXIMUM_ARRAY_LENGTH * 7 - 6)
```

**Comment by laizy** [comment]
this is restricted at:
https://github.com/ontio/ontology/blob/176a1ba39585a16dc52d7b1399753d40a539cf4a/vm/neovm/types/struct.go#L30

**Comment by WyattMufson** [comment]
@laizy that's interesting. I've found that 7 layers seems to be the limit.

I documented it here: https://github.com/TowerBuilders/Ontology-Advanced-Storage-Objects

**Comment by WyattMufson** [comment]
@laizy it also looks like 

https://github.com/ontio/ontology/blob/176a1ba39585a16dc52d7b1399753d40a539cf4a/vm/neovm/types/struct.go#L107

is never called. The other function I listed before does check the depth though.

**Comment by WyattMufson** [comment]
I understand why I'm getting 7 layers.

The `packed` array on the `DynamicList` is 1.
The specific `PackedList` in the `packed` array is 2.
The `array` field in the `PackedList` is 3.
