### ISSUE TITLE
leader proposer

### ISSUE THREAD

**Issue by zhaoguojie2010** [ontio/ontology#947]
Hello, I see that ont has leader-proposer and 2nd-proposer. It's possible that the leader-proposer can manipulate the block it generates so that it continues to be the leader-proposer in next round since only proposal from leader-proposer is accepted before timeout. I think it's a critical issue, what do you think of it?

**Comment by qiluge** [comment]
The proposer of each block is generated from vrf, and the random seed of vrf depends on last block attribute. So every proposer is randomly generated.

**Comment by Honglei-Cong** [comment]
#960
