### ISSUE TITLE
shard consensus get new chainconfig from event store

### ISSUE THREAD

**Issue by xiemylogos** [ontio/ontology#973]
#### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: I'm facing an issue when [...]

#### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

#### Additional context
Add any other context or screenshots about the feature request.

In shard consenus,get new chainconfig from event store db

**Comment by Honglei-Cong** [comment]
fixed by #976 and #993
